import { DashboardData } from "@/types/dashboard";

export const MOCK_DASHBOARD_DATA: DashboardData = {
  timeframe: "Last 30 Days (Q3 2026)",
  criticalAlertsCount: 2,
  businessStatus: {
    label: "Business Health: Healthy",
    variant: "positive",
    lastRefreshTime: "Just now (Live Telemetry)",
  },
  kpis: {
    revenue: {
      id: "metric_rev",
      label: "Revenue",
      value: "₹48.2 Cr",
      changePercentage: 8.4,
      changeText: "+8.4%",
      trend: "up",
      status: "positive",
      timeframe: "vs prior period",
      tooltip: "Consolidated enterprise net revenue across all operating subsidiaries.",
    },
    grossProfit: {
      id: "metric_profit",
      label: "Gross Profit",
      value: "₹19.6 Cr",
      changePercentage: 6.7,
      changeText: "+6.7%",
      trend: "up",
      status: "positive",
      timeframe: "vs prior period",
      tooltip: "Gross margin profit after direct cost of goods and delivery fulfillment.",
    },
    orders: {
      id: "metric_orders",
      label: "Orders",
      value: "14,820",
      changePercentage: 11.2,
      changeText: "+11.2%",
      trend: "up",
      status: "positive",
      timeframe: "vs prior period",
      tooltip: "Total enterprise transaction volume fulfilled with 99.4% SLA adherence.",
    },
    inventory: {
      id: "metric_inventory",
      label: "Inventory",
      value: "₹6.4 Cr",
      changePercentage: -3.1,
      changeText: "−3.1%",
      trend: "down",
      status: "positive",
      timeframe: "working capital freed",
      tooltip: "Buffer inventory optimized through regional warehouse rebalancing.",
    },
    operatingMargin: {
      id: "metric_margin",
      label: "Operating Margin",
      value: "32.4%",
      changePercentage: 2.4,
      changeText: "+2.4 pp",
      trend: "up",
      status: "positive",
      timeframe: "EBITDA margin",
      tooltip: "Net operating margin after variable and fixed operating expenditure.",
    },
    businessHealth: {
      id: "metric_health",
      label: "Business Health",
      value: "96 / 100",
      changePercentage: 4.2,
      changeText: "+4.2 pts",
      trend: "up",
      status: "positive",
      timeframe: "composite index",
      tooltip: "Weighted multi-factor score across growth, margin, liquidity, and demand.",
    },
  },
  performanceSeries: {
    "7D": [
      { date: "Day 1", revenue: 6.4, grossProfit: 2.6, ordersCount: 2040 },
      { date: "Day 2", revenue: 6.8, grossProfit: 2.8, ordersCount: 2110 },
      { date: "Day 3", revenue: 6.5, grossProfit: 2.7, ordersCount: 2080 },
      { date: "Day 4", revenue: 7.2, grossProfit: 3.0, ordersCount: 2240 },
      { date: "Day 5", revenue: 7.0, grossProfit: 2.9, ordersCount: 2190 },
      { date: "Day 6", revenue: 7.5, grossProfit: 3.1, ordersCount: 2310 },
      { date: "Day 7", revenue: 7.8, grossProfit: 3.3, ordersCount: 2450 },
    ],
    "30D": [
      { date: "Week 1", revenue: 10.8, grossProfit: 4.3, ordersCount: 3400 },
      { date: "Week 2", revenue: 11.6, grossProfit: 4.7, ordersCount: 3620 },
      { date: "Week 3", revenue: 12.4, grossProfit: 5.1, ordersCount: 3850 },
      { date: "Week 4", revenue: 13.4, grossProfit: 5.5, ordersCount: 4100 },
    ],
    "90D": [
      { date: "Month 1 (Jul)", revenue: 42.1, grossProfit: 16.8, ordersCount: 12800 },
      { date: "Month 2 (Aug)", revenue: 45.4, grossProfit: 18.2, ordersCount: 13900 },
      { date: "Month 3 (Sep)", revenue: 48.2, grossProfit: 19.6, ordersCount: 14820 },
    ],
  },
  health: {
    compositeScore: 96,
    status: "healthy",
    lastAuditTimestamp: "2026-09-29T10:15:00Z",
    indicators: [
      {
        name: "Revenue Growth",
        score: 94,
        metricValue: "+8.4% YoY",
        status: "healthy",
        trend: "up",
        detail: "Top-line expansion outpacing category benchmarks.",
      },
      {
        name: "Margin Health",
        score: 98,
        metricValue: "32.4% EBITDA",
        status: "healthy",
        trend: "up",
        detail: "Pricing leverage yielding +240 bps EBITDA expansion.",
      },
      {
        name: "Inventory Health",
        score: 92,
        metricValue: "12.4x Turnover",
        status: "healthy",
        trend: "up",
        detail: "Working capital freed; zero stockout incidents across hubs.",
      },
      {
        name: "Market Demand",
        score: 96,
        metricValue: "14,820 Daily Vol",
        status: "healthy",
        trend: "up",
        detail: "Enterprise buyer inbound volume up 11.2%.",
      },
      {
        name: "Conversion Efficiency",
        score: 82,
        metricValue: "−8.2% in Tier-2",
        status: "warning",
        trend: "down",
        detail: "CAC escalation detected in mid-market funnel cohort.",
      },
    ],
  },
  intelligenceSignal: {
    headline: "Revenue Efficiency Divergence Detected",
    summary: "Revenue is growing (+8.4%), but underlying revenue efficiency is deteriorating due to declining conversion in Tier-2 channels (−8.2%) coupled with increasing acquisition cost (+14.1%).",
    confidenceScore: 92,
    supportingMetrics: [
      { label: "Conversion Rate", delta: "↓ 8.2%", trend: "down", status: "warning" },
      { label: "Customer Acq. Cost", delta: "↑ 14.1%", trend: "up", status: "negative" },
      { label: "Gross Revenue", delta: "+8.4%", trend: "up", status: "positive" },
      { label: "Operating Margin", delta: "+2.4 pp", trend: "up", status: "positive" },
    ],
    recommendedRoute: "/investigation",
    recommendedActionLabel: "Investigate Root Cause",
  },
  recommendedSteps: [
    {
      id: "step_1",
      stepNumber: 1,
      title: "Investigate declining conversion",
      description: "Decompose root cause telemetry across APM gateway latency and funnel checkout steps.",
      route: "/investigation",
      engineName: "Deep Anomaly Investigation",
      badge: "Root Cause",
    },
    {
      id: "step_2",
      stepNumber: 2,
      title: "Replay previous marketing allocation",
      description: "Compare empirical historical spend against counterfactual optimal distribution in Q2.",
      route: "/replay",
      engineName: "Decision Replay Engine",
      badge: "Counterfactual",
    },
    {
      id: "step_3",
      stepNumber: 3,
      title: "Simulate alternative campaign allocations",
      description: "Stress-test 10k Monte Carlo runs adjusting marketing budget and price elasticity levers.",
      route: "/scenario",
      engineName: "Scenario Simulation Lab",
      badge: "Monte Carlo",
    },
    {
      id: "step_4",
      stepNumber: 4,
      title: "Evaluate constrained budget optimization",
      description: "Solve Pareto frontier respecting hard constraints: Budget ≤ ₹2M and Margin ≥ 25%.",
      route: "/optimizer",
      engineName: "Multi-Objective Optimizer",
      badge: "Pareto Optimal",
    },
  ],
  radarPoints: [
    {
      id: "r1",
      code: "OPP-9021",
      title: "Revenue Efficiency Decline",
      impactLevel: "high",
      urgencyLevel: "high",
      netValue: 28000000, // ₹2.8 Cr
      confidence: 91,
      category: "Pricing & Margin",
      route: "/investigation",
    },
    {
      id: "r2",
      code: "OPP-9023",
      title: "Inventory Buffer Imbalance",
      impactLevel: "high",
      urgencyLevel: "low",
      netValue: 8400000, // ₹84 L
      confidence: 87,
      category: "Supply Chain",
      route: "/opportunities",
    },
    {
      id: "r3",
      code: "OPP-9022",
      title: "Healthcare Churn Escalation",
      impactLevel: "low",
      urgencyLevel: "high",
      netValue: 19700000, // ₹1.97 Cr
      confidence: 88,
      category: "Retention",
      route: "/investigation",
    },
    {
      id: "r4",
      code: "OPP-9025",
      title: "Fintech Cross-Sell Expansion",
      impactLevel: "low",
      urgencyLevel: "low",
      netValue: 4500000, // ₹45 L
      confidence: 82,
      category: "Growth",
      route: "/opportunities",
    },
  ],
  pipeline: {
    activeOpportunitiesCount: 12,
    totalOpportunityValue: 34200000,
    pendingInvestigationsCount: 4,
    activeOptimizationsCount: 6,
    automatedExecutionRate: 68.5,
  },
  recentActivities: [
    {
      id: "act_1",
      title: "Pricing Indexation Executed",
      description: "Automated real-time tier adjustment for Mid-Market accounts (+₹3.4M net lift).",
      timestamp: "2026-09-29T10:45:00Z",
      timeAgo: "14:32",
      type: "decision",
      severity: "low",
      actor: { id: "usr_1", name: "Alexandra Chen" },
    },
    {
      id: "act_2",
      title: "Opportunity Detected: Revenue Efficiency Decline",
      description: "Conversion drop of 8.2% flagged in Tier-2 accounts ($2.8M EBITDA impact).",
      timestamp: "2026-09-29T09:15:00Z",
      timeAgo: "13:47",
      type: "alert",
      severity: "critical",
      actor: { id: "sys_1", name: "Opportunity Radar" },
    },
    {
      id: "act_3",
      title: "Investigation Completed: SLA Gateway Root Cause",
      description: "P99 HTTP 504 timeout cluster identified as root driver of customer churn risk.",
      timestamp: "2026-09-29T08:30:00Z",
      timeAgo: "12:18",
      type: "investigation",
      severity: "medium",
      actor: { id: "usr_2", name: "Dr. Ethan Ramos" },
    },
    {
      id: "act_4",
      title: "Scenario Simulation #5501 Generated",
      description: "10,000 Monte Carlo iterations evaluated for raw materials cost shock.",
      timestamp: "2026-09-29T07:45:00Z",
      timeAgo: "11:52",
      type: "scenario",
      severity: "low",
      actor: { id: "usr_3", name: "Marcus Vance" },
    },
  ],
};
