import type {
  DecisionDNARecord,
  DecisionDNASummaryStats,
  DecisionDNA,
} from "@/types/decision-dna";

export const MOCK_DECISION_DNA_STATS: DecisionDNASummaryStats = {
  totalDecisions: 28,
  approved: 18,
  modified: 6,
  rejected: 4,
  averageConfidence: 84,
  decisionsWithOutcomes: 21,
};

export const MOCK_DECISION_DNA_RECORDS: DecisionDNARecord[] = [
  {
    id: "DNA-2026-001",
    decisionId: "DEC-2026-REV-021",
    title: "Revenue Efficiency Recovery",
    type: "optimization",
    status: "approved",
    createdAt: "2026-09-29T14:32:00Z",
    decisionDate: "2026-09-29T14:48:00Z",
    owner: "Alexandra Chen",
    organization: "UrbanCart Retail Dynamics",
    opportunityId: "OPP-9021",
    trigger: {
      problemTitle: "Revenue Efficiency Deterioration in Q3 Performance Channels",
      description:
        "Customer Acquisition Cost (CAC) spiked by +14.1% across paid acquisition channels while gross margin fell 2.4 pp below quarterly board target.",
      detectedAt: "2026-09-29T08:00:00Z",
      metricAlert: "CAC +14.1% YoY, Margin -2.4 pp",
      opportunityId: "OPP-9021",
    },
    businessQuestion:
      "How can we reallocate marketing spend and balance inventory/pricing to recover ₹22.4 Cr gross profit without exceeding churn tolerance?",
    summary:
      "Reallocated performance marketing spend toward higher-efficiency channels and scaled unit price from ₹105 to ₹108 while maintaining safety inventory at 1,050 units under strict 3.5% churn limits.",
    currentConfiguration: {
      marketingBudget: "₹1.40 Cr",
      workingInventory: "900 units",
      unitPrice: "₹105",
      expectedRevenue: "₹48.2 Cr",
      expectedProfit: "₹19.6 Cr",
      expectedMargin: "32.4%",
      orders: "460,000",
      inventoryLevels: "900 buffer units",
    },
    recommendedConfiguration: {
      marketingBudget: "₹1.65 Cr",
      workingInventory: "1,050 units",
      unitPrice: "₹108",
      expectedRevenue: "₹53.1 Cr",
      expectedProfit: "₹22.4 Cr",
      expectedMargin: "34.6%",
      orders: "492,000",
      inventoryLevels: "1,050 buffer units",
    },
    selectedConfiguration: {
      marketingBudget: "₹1.65 Cr",
      workingInventory: "1,050 units",
      unitPrice: "₹108",
      expectedRevenue: "₹53.1 Cr",
      expectedProfit: "₹22.4 Cr",
      expectedMargin: "34.6%",
      orders: "492,000",
      inventoryLevels: "1,050 buffer units",
    },
    evidence: [
      {
        id: "ev-1",
        signal: "Revenue Elasticity Signal",
        detail: "Marginal CAC efficiency peaks between ₹1.60 Cr and ₹1.70 Cr spend envelope.",
        metricImpact: "Revenue +8.4%",
        confidenceContribution: 22,
        source: "Multi-factor Econometric Model",
        timestamp: "2026-09-29T09:15:00Z",
        type: "efficiency",
      },
      {
        id: "ev-2",
        signal: "Price Inelasticity Cohort",
        detail: "Tier-1 enterprise accounts exhibit <0.2% price sensitivity for modest ₹3 indexation.",
        metricImpact: "Operating Margin +2.4 pp",
        confidenceContribution: 28,
        source: "Counterfactual Replay Engine",
        timestamp: "2026-09-29T10:30:00Z",
        type: "price",
      },
      {
        id: "ev-3",
        signal: "Warehouse Fill Rate Buffer",
        detail: "1,050 units working inventory maintains 98.2% service level with zero regional stockout risk.",
        metricImpact: "Inventory -3.1% holding cost",
        confidenceContribution: 18,
        source: "Supply Chain Telemetry",
        timestamp: "2026-09-29T11:45:00Z",
        type: "inventory",
      },
      {
        id: "ev-4",
        signal: "Paid Channel CAC Curve",
        detail: "Paid social saturation reached; shifting ₹25L to search intent captures high-intent buyers.",
        metricImpact: "CAC -11.2% blended",
        confidenceContribution: 16,
        source: "Investigation INV-2026-044",
        timestamp: "2026-09-29T12:00:00Z",
        type: "sensitivity",
      },
    ],
    alternatives: [
      {
        id: "alt-a",
        name: "Option A: Maintain Current Allocation",
        description: "Keep ₹1.40 Cr marketing budget and ₹105 price; avoid operational change.",
        marketingBudget: "₹1.40 Cr",
        workingInventory: "900 units",
        unitPrice: "₹105",
        expectedRevenue: "₹48.2 Cr",
        expectedProfit: "₹19.6 Cr",
        expectedMargin: "32.4%",
        constraintsSatisfied: true,
        confidence: 90,
        status: "not_selected",
        rejectionReason: "Leaves ₹2.8 Cr in unrealized gross profit on the table.",
      },
      {
        id: "alt-b",
        name: "Option B: Aggressive Top-Line Expansion",
        description: "Push marketing budget to ₹1.95 Cr limit and drop price to ₹102.",
        marketingBudget: "₹1.95 Cr",
        workingInventory: "1,400 units",
        unitPrice: "₹102",
        expectedRevenue: "₹57.4 Cr",
        expectedProfit: "₹20.9 Cr",
        expectedMargin: "30.8%",
        constraintsSatisfied: true,
        confidence: 76,
        status: "considered",
        rejectionReason: "Eats into operating margin; risks violating 3.5% churn limit under surge demand.",
      },
      {
        id: "alt-c",
        name: "Option C: Efficiency-Focused Optimization (Recommended)",
        description: "Balanced Pareto optimization with ₹1.65 Cr budget, 1,050 inventory, and ₹108 unit price.",
        marketingBudget: "₹1.65 Cr",
        workingInventory: "1,050 units",
        unitPrice: "₹108",
        expectedRevenue: "₹53.1 Cr",
        expectedProfit: "₹22.4 Cr",
        expectedMargin: "34.6%",
        constraintsSatisfied: true,
        confidence: 84,
        status: "selected",
      },
      {
        id: "alt-d",
        name: "Option D: Pure Margin Protection",
        description: "Scale price to ₹116 and slash marketing to ₹1.15 Cr to maximize margin rate.",
        marketingBudget: "₹1.15 Cr",
        workingInventory: "750 units",
        unitPrice: "₹116",
        expectedRevenue: "₹44.0 Cr",
        expectedProfit: "₹19.8 Cr",
        expectedMargin: "38.5%",
        constraintsSatisfied: false,
        confidence: 68,
        status: "rejected",
        rejectionReason: "Violated minimum annual revenue volume constraints.",
      },
    ],
    constraints: [
      {
        id: "c-1",
        name: "Marketing Budget Envelope",
        rule: "Budget ≤ ₹2.00 Cr",
        requiredLimit: "₹2.00 Cr",
        selectedValue: "₹1.65 Cr",
        status: "satisfied",
        slack: "₹0.35 Cr remaining",
      },
      {
        id: "c-2",
        name: "Minimum Operating Margin Floor",
        rule: "Margin ≥ 25.0%",
        requiredLimit: "25.0%",
        selectedValue: "34.6%",
        status: "satisfied",
        slack: "9.6 pp safety buffer",
      },
      {
        id: "c-3",
        name: "Warehouse Inventory Capacity",
        rule: "Inventory ≤ 1,500 units",
        requiredLimit: "1,500 units",
        selectedValue: "1,050 units",
        status: "satisfied",
        slack: "450 units headroom",
      },
      {
        id: "c-4",
        name: "Annual Customer Churn Ceiling",
        rule: "Churn ≤ 3.5%",
        requiredLimit: "3.5%",
        selectedValue: "3.1%",
        status: "binding",
        slack: "0.4 pp safety buffer",
      },
    ],
    humanDecision: {
      decisionMaker: "Alexandra Chen",
      role: "Chief Strategy & Operating Officer",
      action: "approved",
      decidedAt: "2026-09-29T14:48:00Z",
      reason:
        "Approved the recommended configuration without changes following complete review of constraint verification and Monte Carlo confidence intervals.",
    },
    expectedOutcome: {
      marketingBudget: "₹1.65 Cr",
      workingInventory: "1,050 units",
      unitPrice: "₹108",
      expectedRevenue: "₹53.1 Cr",
      expectedProfit: "₹22.4 Cr",
      expectedMargin: "34.6%",
    },
    actualOutcome: {
      status: "achieved",
      recordedAt: "2026-09-29T17:30:00Z",
      explanation:
        "Post-decision performance validated after 30-day tracking window. Gross profit captured at ₹22.1 Cr with stable 34.2% margin.",
      summary: "98.7% target attainment across all primary financial KPIs.",
      metrics: [
        {
          metric: "Gross Profit",
          expected: "₹22.4 Cr",
          actual: "₹22.1 Cr",
          variance: "-₹0.3 Cr (-1.3%)",
          varianceType: "neutral",
        },
        {
          metric: "Top-Line Revenue",
          expected: "₹53.1 Cr",
          actual: "₹52.8 Cr",
          variance: "-₹0.3 Cr (-0.6%)",
          varianceType: "neutral",
        },
        {
          metric: "Operating Margin",
          expected: "34.6%",
          actual: "34.2%",
          variance: "-0.4 pp",
          varianceType: "neutral",
        },
        {
          metric: "Total Orders Delivered",
          expected: "492,000",
          actual: "489,500",
          variance: "-2,500 (-0.5%)",
          varianceType: "neutral",
        },
        {
          metric: "Annualized Churn",
          expected: "3.1%",
          actual: "3.05%",
          variance: "-0.05 pp (Better)",
          varianceType: "positive",
        },
      ],
    },
    uncertainty: {
      confidence: 84,
      baseCaseProfit: "₹22.4 Cr",
      downsideProfit: "₹21.2 Cr",
      upsideProfit: "₹23.1 Cr",
      revenueRange: "₹50.8 Cr — ₹54.6 Cr",
      grossProfitRange: "₹21.2 Cr — ₹23.1 Cr",
      keyDrivers: [
        "Customer conversion elasticity in Q3 paid channels",
        "Competitor promotional retaliation in Tier-2 SaaS segment",
        "Warehouse overtime fulfillment labor variance",
      ],
    },
    learning: {
      isAvailable: true,
      whatWeExpected:
        "Efficiency-focused allocation would increase gross profit to ₹22.4 Cr while maintaining margin above 34.5%.",
      whatHappened:
        "Actual gross profit materialized at ₹22.1 Cr. Revenue lift was slightly moderated by mid-month macro ad rate fluctuations.",
      whatWeLearned:
        "Channel efficiency shifted faster than expected into high-intent search, lowering CAC even further while volume stabilized.",
      nextTimeConsideration:
        "Introduce dynamic weekly ad channel rebalancing instead of monthly fixed allocation locks.",
    },
    lineage: [
      {
        stage: "Opportunity",
        id: "OPP-9021",
        status: "completed",
        timestamp: "08:00 UTC",
        route: "/opportunities/OPP-9021",
        description: "Detected revenue efficiency deterioration",
      },
      {
        stage: "Investigation",
        id: "INV-2026-044",
        status: "completed",
        timestamp: "09:15 UTC",
        route: "/investigation?opportunity=OPP-9021",
        description: "Proven causality between CAC spike and channel saturation",
      },
      {
        stage: "Evidence",
        id: "EVD-8802",
        status: "completed",
        timestamp: "10:30 UTC",
        route: "/investigation?opportunity=OPP-9021",
        description: "16 telemetry signals and elasticity models verified",
      },
      {
        stage: "Decision Replay",
        id: "REP-2026-018",
        status: "completed",
        timestamp: "11:45 UTC",
        route: "/replay",
        description: "Counterfactual replay tested against Q2 2025 baseline",
      },
      {
        stage: "Scenario",
        id: "SCN-2026-081",
        status: "completed",
        timestamp: "12:30 UTC",
        route: "/scenario",
        description: "Simulated 4 multi-lever business configurations",
      },
      {
        stage: "Optimization",
        id: "OPT-2026-042",
        status: "completed",
        timestamp: "14:15 UTC",
        route: "/optimizer",
        description: "1,260 candidates evaluated; #742 identified as Pareto optimal",
      },
      {
        stage: "Human Approval",
        id: "DEC-2026-REV-021",
        status: "completed",
        timestamp: "14:48 UTC",
        route: "/decisions",
        description: "Executive quorum approved by Alexandra Chen (CSOO)",
      },
      {
        stage: "Decision DNA",
        id: "DNA-2026-001",
        status: "active",
        timestamp: "17:30 UTC",
        route: "/decision-dna",
        description: "Immutable decision lineage and learning archived",
      },
    ],
    provenance: {
      dnaId: "DNA-2026-001",
      decisionId: "DEC-2026-REV-021",
      opportunityId: "OPP-9021",
      investigationId: "INV-2026-044",
      replayId: "REP-2026-018",
      scenarioId: "SCN-2026-081",
      optimizationId: "OPT-2026-042",
      verifiedBy: "Governance Engine (SHA-256 Mock Checksum #88a1b9)",
      recordedAt: "2026-09-29T17:30:00Z",
    },
    auditEvents: [
      {
        id: "ae-1",
        timestamp: "2026-09-29T08:00:00Z",
        time: "08:00 UTC",
        actor: "Continuous Telemetry Daemon",
        event: "Opportunity Detected",
        description: "Triggered alert for CAC spike and gross margin deterioration.",
        type: "detected",
      },
      {
        id: "ae-2",
        timestamp: "2026-09-29T09:15:00Z",
        time: "09:15 UTC",
        actor: "DecisionOS Root Cause Engine",
        event: "Investigation Completed",
        description: "Hypothesis #2 validated with 88% causal probability.",
        type: "investigated",
      },
      {
        id: "ae-3",
        timestamp: "2026-09-29T12:30:00Z",
        time: "12:30 UTC",
        actor: "Alexandra Chen",
        event: "Scenario Simulation Run",
        description: "Created 4 lever permutations in Scenario Lab.",
        type: "simulated",
      },
      {
        id: "ae-4",
        timestamp: "2026-09-29T14:15:00Z",
        time: "14:15 UTC",
        actor: "Pareto Convex Solver",
        event: "Optimization Solved",
        description: "Config #742 recommended in 1,420ms solver time.",
        type: "optimized",
      },
      {
        id: "ae-5",
        timestamp: "2026-09-29T14:35:00Z",
        time: "14:35 UTC",
        actor: "Alexandra Chen",
        event: "Decision Review Started",
        description: "Examined constraint slack, sensitivity, and uncertainty intervals.",
        type: "reviewed",
      },
      {
        id: "ae-6",
        timestamp: "2026-09-29T14:48:00Z",
        time: "14:48 UTC",
        actor: "Alexandra Chen (CSOO)",
        event: "Human Authorization Granted",
        description: "Approved recommended configuration without manual modification.",
        type: "authorized",
      },
      {
        id: "ae-7",
        timestamp: "2026-09-29T14:50:00Z",
        time: "14:50 UTC",
        actor: "Decision Registry",
        event: "Decision Recorded",
        description: "Stored authoritative governance record DEC-2026-REV-021.",
        type: "recorded",
      },
      {
        id: "ae-8",
        timestamp: "2026-09-29T17:30:00Z",
        time: "17:30 UTC",
        actor: "Outcome Telemetry Tracker",
        event: "Outcome Recorded & Learning Updated",
        description: "30-day tracking window finalized with 98.7% target attainment.",
        type: "learning_updated",
      },
    ],
    confidence: 84,
  },
  {
    id: "DNA-2026-002",
    decisionId: "DEC-2026-MKT-018",
    title: "Q2 Marketing Allocation Adjustment",
    type: "optimization",
    status: "modified",
    createdAt: "2026-09-28T11:00:00Z",
    decisionDate: "2026-09-28T16:20:00Z",
    owner: "Marcus Vance",
    organization: "UrbanCart Retail Dynamics",
    opportunityId: "OPP-8802",
    trigger: {
      problemTitle: "Underperforming Mid-Market Growth Velocity",
      description: "Mid-market enterprise expansion lagged forecast by -18% due to insufficient top-of-funnel pipeline.",
      detectedAt: "2026-09-28T09:00:00Z",
      metricAlert: "Pipeline Velocity -18% vs plan",
      opportunityId: "OPP-8802",
    },
    businessQuestion:
      "Can we expand marketing spend without compromising operating margin envelope?",
    summary:
      "Optimizer recommended ₹2.20 Cr budget; human decision-maker modified allocation to ₹1.85 Cr to preserve cash reserves while lifting unit price to ₹110.",
    currentConfiguration: {
      marketingBudget: "₹1.50 Cr",
      workingInventory: "900 units",
      unitPrice: "₹105",
      expectedRevenue: "₹46.0 Cr",
      expectedProfit: "₹18.5 Cr",
      expectedMargin: "32.0%",
    },
    recommendedConfiguration: {
      marketingBudget: "₹2.20 Cr",
      workingInventory: "950 units",
      unitPrice: "₹110",
      expectedRevenue: "₹58.5 Cr",
      expectedProfit: "₹24.0 Cr",
      expectedMargin: "35.8%",
    },
    selectedConfiguration: {
      marketingBudget: "₹1.85 Cr",
      workingInventory: "950 units",
      unitPrice: "₹110",
      expectedRevenue: "₹55.2 Cr",
      expectedProfit: "₹22.8 Cr",
      expectedMargin: "36.2%",
    },
    evidence: [
      {
        id: "ev-m1",
        signal: "Enterprise Pipeline Conversion",
        detail: "Mid-market sales cycle accelerates with targeted ABM campaigns.",
        metricImpact: "Pipeline +24%",
        confidenceContribution: 25,
        source: "CRM Telemetry",
        timestamp: "2026-09-28T11:30:00Z",
        type: "efficiency",
      },
    ],
    alternatives: [
      {
        id: "alt-m1",
        name: "Recommended: ₹2.20 Cr Spend",
        description: "Full budget expansion as suggested by solver.",
        marketingBudget: "₹2.20 Cr",
        workingInventory: "950 units",
        unitPrice: "₹110",
        expectedRevenue: "₹58.5 Cr",
        expectedProfit: "₹24.0 Cr",
        expectedMargin: "35.8%",
        constraintsSatisfied: true,
        confidence: 82,
        status: "considered",
        rejectionReason: "Human modified to reduce capex risk.",
      },
      {
        id: "alt-m2",
        name: "Human Modified: ₹1.85 Cr Spend",
        description: "Conservative budget increase balancing growth with reserve safety.",
        marketingBudget: "₹1.85 Cr",
        workingInventory: "950 units",
        unitPrice: "₹110",
        expectedRevenue: "₹55.2 Cr",
        expectedProfit: "₹22.8 Cr",
        expectedMargin: "36.2%",
        constraintsSatisfied: true,
        confidence: 88,
        status: "selected",
      },
    ],
    constraints: [
      {
        id: "c-m1",
        name: "Capex Limit",
        rule: "Budget ≤ ₹2.00 Cr",
        requiredLimit: "₹2.00 Cr",
        selectedValue: "₹1.85 Cr",
        status: "satisfied",
        slack: "₹0.15 Cr",
      },
    ],
    humanDecision: {
      decisionMaker: "Marcus Vance",
      role: "VP Engineering & Product Ops",
      action: "modified",
      decidedAt: "2026-09-28T16:20:00Z",
      reason: "Scaled down marketing budget from ₹2.20 Cr to ₹1.85 Cr to maintain conservative quarterly cash reserve.",
      modificationDetails: {
        originalMarketing: "₹2.20 Cr",
        modifiedMarketing: "₹1.85 Cr",
        originalInventory: "950 units",
        modifiedInventory: "950 units",
        originalPrice: "₹110",
        modifiedPrice: "₹110",
        rationale: "Preserved ₹35L cash buffer without meaningful top-line penalty.",
      },
    },
    expectedOutcome: {
      marketingBudget: "₹1.85 Cr",
      workingInventory: "950 units",
      unitPrice: "₹110",
      expectedRevenue: "₹55.2 Cr",
      expectedProfit: "₹22.8 Cr",
      expectedMargin: "36.2%",
    },
    actualOutcome: {
      status: "achieved",
      recordedAt: "2026-09-29T16:00:00Z",
      explanation: "Delivered ₹22.6 Cr gross profit with a 36.0% operating margin.",
      summary: "99.1% goal attainment with zero cash flow strain.",
      metrics: [
        {
          metric: "Gross Profit",
          expected: "₹22.8 Cr",
          actual: "₹22.6 Cr",
          variance: "-₹0.2 Cr (-0.9%)",
          varianceType: "neutral",
        },
        {
          metric: "Revenue",
          expected: "₹55.2 Cr",
          actual: "₹54.9 Cr",
          variance: "-₹0.3 Cr (-0.5%)",
          varianceType: "neutral",
        },
      ],
    },
    uncertainty: {
      confidence: 88,
      baseCaseProfit: "₹22.8 Cr",
      downsideProfit: "₹21.5 Cr",
      upsideProfit: "₹23.5 Cr",
      revenueRange: "₹53.0 Cr — ₹56.5 Cr",
      grossProfitRange: "₹21.5 Cr — ₹23.5 Cr",
      keyDrivers: ["Sales hiring ramp velocity", "Q3 enterprise buying cycles"],
    },
    learning: {
      isAvailable: true,
      whatWeExpected: "Conservative ₹1.85 Cr spend would preserve 36% margin with steady pipeline growth.",
      whatHappened: "Margin hit exactly 36.0% with strong enterprise conversion.",
      whatWeLearned: "Modifying solver recommendations with human executive context prevented unnecessary cash strain.",
      nextTimeConsideration: "Incorporate explicit cash reserve threshold directly into solver objective function.",
    },
    lineage: [
      {
        stage: "Opportunity",
        id: "OPP-8802",
        status: "completed",
        timestamp: "09:00 UTC",
        route: "/opportunities/OPP-8802",
        description: "Pipeline growth lag detected",
      },
      {
        stage: "Investigation",
        id: "INV-2026-039",
        status: "completed",
        timestamp: "11:00 UTC",
        route: "/investigation",
        description: "Top-of-funnel bottleneck proven",
      },
      {
        stage: "Optimization",
        id: "OPT-2026-038",
        status: "completed",
        timestamp: "14:00 UTC",
        route: "/optimizer",
        description: "Recommended ₹2.20 Cr expansion",
      },
      {
        stage: "Human Approval",
        id: "DEC-2026-MKT-018",
        status: "completed",
        timestamp: "16:20 UTC",
        route: "/decisions",
        description: "Modified to ₹1.85 Cr by Marcus Vance",
      },
      {
        stage: "Decision DNA",
        id: "DNA-2026-002",
        status: "active",
        timestamp: "16:00 UTC",
        route: "/decision-dna",
        description: "Preserved modified decision and outcome",
      },
    ],
    provenance: {
      dnaId: "DNA-2026-002",
      decisionId: "DEC-2026-MKT-018",
      opportunityId: "OPP-8802",
      investigationId: "INV-2026-039",
      replayId: "REP-2026-012",
      scenarioId: "SCN-2026-077",
      optimizationId: "OPT-2026-038",
      verifiedBy: "Governance Engine (SHA-256 Mock Checksum #44c8f1)",
      recordedAt: "2026-09-29T16:00:00Z",
    },
    auditEvents: [
      {
        id: "ae-m1",
        timestamp: "2026-09-28T09:00:00Z",
        time: "09:00 UTC",
        actor: "Pipeline Telemetry",
        event: "Opportunity Detected",
        description: "Alert for pipeline velocity lag.",
        type: "detected",
      },
      {
        id: "ae-m2",
        timestamp: "2026-09-28T16:20:00Z",
        time: "16:20 UTC",
        actor: "Marcus Vance",
        event: "Decision Modified & Authorized",
        description: "Adjusted budget to ₹1.85 Cr.",
        type: "authorized",
      },
    ],
    confidence: 88,
  },
  {
    id: "DNA-2026-003",
    decisionId: "DEC-2026-SCM-044",
    title: "Inventory Rebalancing Across North Hubs",
    type: "scenario",
    status: "outcome_pending",
    createdAt: "2026-09-29T11:40:00Z",
    decisionDate: "2026-09-29T12:20:00Z",
    owner: "Operations Team",
    organization: "UrbanCart Retail Dynamics",
    opportunityId: "OPP-7412",
    trigger: {
      problemTitle: "Regional Stockout Risk in Delhi Hub",
      description: "Northern region delivery SLA breaches reached 8.2% due to buffer inventory misallocation.",
      detectedAt: "2026-09-29T10:00:00Z",
      metricAlert: "Stockout rate 8.2%",
      opportunityId: "OPP-7412",
    },
    businessQuestion:
      "How to eliminate Northern regional stockouts with minimal transit rebalancing cost?",
    summary:
      "Shifted 350 buffer units from Mumbai central depot to Delhi North hub to eliminate regional delivery delays.",
    currentConfiguration: {
      marketingBudget: "₹1.10 Cr",
      workingInventory: "900 units",
      unitPrice: "₹105",
      expectedRevenue: "₹47.0 Cr",
      expectedProfit: "₹18.7 Cr",
      expectedMargin: "32.5%",
    },
    recommendedConfiguration: {
      marketingBudget: "₹1.10 Cr",
      workingInventory: "1,250 units",
      unitPrice: "₹105",
      expectedRevenue: "₹49.8 Cr",
      expectedProfit: "₹20.1 Cr",
      expectedMargin: "33.1%",
    },
    selectedConfiguration: {
      marketingBudget: "₹1.10 Cr",
      workingInventory: "1,250 units",
      unitPrice: "₹105",
      expectedRevenue: "₹49.8 Cr",
      expectedProfit: "₹20.1 Cr",
      expectedMargin: "33.1%",
    },
    evidence: [
      {
        id: "ev-s1",
        signal: "Transit Velocity Signal",
        detail: "Northern stockouts drop from 8.2% to 1.1% upon reallocation.",
        metricImpact: "Service level +7.1%",
        confidenceContribution: 30,
        source: "Supply Chain Scenario Model",
        timestamp: "2026-09-29T11:30:00Z",
        type: "inventory",
      },
    ],
    alternatives: [
      {
        id: "alt-s1",
        name: "Rebalance 350 Units (Selected)",
        description: "Inter-state redistribution across primary depots.",
        marketingBudget: "₹1.10 Cr",
        workingInventory: "1,250 units",
        unitPrice: "₹105",
        expectedRevenue: "₹49.8 Cr",
        expectedProfit: "₹20.1 Cr",
        expectedMargin: "33.1%",
        constraintsSatisfied: true,
        confidence: 78,
        status: "selected",
      },
    ],
    constraints: [
      {
        id: "c-s1",
        name: "Logistics Budget Cap",
        rule: "Spend ≤ ₹1.50 Cr",
        requiredLimit: "₹1.50 Cr",
        selectedValue: "₹1.10 Cr",
        status: "satisfied",
        slack: "₹0.40 Cr",
      },
    ],
    humanDecision: {
      decisionMaker: "David Thorne",
      role: "VP Supply Chain Operations",
      action: "approved",
      decidedAt: "2026-09-29T12:20:00Z",
      reason: "Approved immediate redistribution to protect customer SLA.",
    },
    expectedOutcome: {
      marketingBudget: "₹1.10 Cr",
      workingInventory: "1,250 units",
      unitPrice: "₹105",
      expectedRevenue: "₹49.8 Cr",
      expectedProfit: "₹20.1 Cr",
      expectedMargin: "33.1%",
    },
    actualOutcome: {
      status: "pending",
      explanation: "Tracking window in progress. Outcome metrics will be recorded at end of billing cycle.",
      summary: "Execution ongoing across 3 regional depots.",
      metrics: [],
    },
    uncertainty: {
      confidence: 78,
      baseCaseProfit: "₹20.1 Cr",
      downsideProfit: "₹19.5 Cr",
      upsideProfit: "₹20.6 Cr",
      revenueRange: "₹48.9 Cr — ₹50.7 Cr",
      grossProfitRange: "₹19.5 Cr — ₹20.6 Cr",
      keyDrivers: ["Carrier fuel surcharges", "Monsoon weather transit delays"],
    },
    learning: {
      isAvailable: false,
      whatWeExpected: "Stockouts will drop below 1.5% with less than ₹20L additional freight cost.",
      whatHappened: "Outcome data collection currently in progress.",
      whatWeLearned: "Learning will become available after outcome data is recorded.",
      nextTimeConsideration: "Establish automated regional rebalancing triggers in ERP.",
    },
    lineage: [
      {
        stage: "Opportunity",
        id: "OPP-7412",
        status: "completed",
        timestamp: "10:00 UTC",
        route: "/opportunities/OPP-7412",
        description: "Northern stockout spike detected",
      },
      {
        stage: "Scenario",
        id: "SCN-2026-088",
        status: "completed",
        timestamp: "11:40 UTC",
        route: "/scenario",
        description: "Simulated depot rebalancing",
      },
      {
        stage: "Human Approval",
        id: "DEC-2026-SCM-044",
        status: "completed",
        timestamp: "12:20 UTC",
        route: "/decisions",
        description: "Approved by Operations",
      },
      {
        stage: "Decision DNA",
        id: "DNA-2026-003",
        status: "active",
        timestamp: "12:30 UTC",
        route: "/decision-dna",
        description: "Outcome tracking active",
      },
    ],
    provenance: {
      dnaId: "DNA-2026-003",
      decisionId: "DEC-2026-SCM-044",
      opportunityId: "OPP-7412",
      investigationId: "INV-2026-031",
      replayId: "REP-2026-009",
      scenarioId: "SCN-2026-088",
      optimizationId: "OPT-2026-039",
      verifiedBy: "Governance Engine (SHA-256 Mock Checksum #12e9b7)",
      recordedAt: "2026-09-29T12:30:00Z",
    },
    auditEvents: [
      {
        id: "ae-s1",
        timestamp: "2026-09-29T10:00:00Z",
        time: "10:00 UTC",
        actor: "Logistics Monitor",
        event: "Stockout Alert Triggered",
        description: "Alert generated for Delhi depot.",
        type: "detected",
      },
    ],
    confidence: 78,
  },
  {
    id: "DNA-2026-004",
    decisionId: "DEC-2026-PRC-091",
    title: "Mid-Tier Dynamic Pricing Adjustment",
    type: "replay",
    status: "approved",
    createdAt: "2026-09-28T15:10:00Z",
    decisionDate: "2026-09-29T09:15:00Z",
    owner: "Finance & Monetization",
    organization: "UrbanCart Retail Dynamics",
    opportunityId: "OPP-6610",
    trigger: {
      problemTitle: "Contract Renewal Yield Gap",
      description: "Historical contract rollover yielded 4.2% below market inflation indexation benchmark.",
      detectedAt: "2026-09-28T14:00:00Z",
      metricAlert: "Yield indexation gap -4.2%",
      opportunityId: "OPP-6610",
    },
    businessQuestion: "Can we apply 6.2% price adjustment across Tier-2 SaaS accounts without increasing churn?",
    summary: "Enacted 6.2% price adjustment across Tier-2 SaaS enterprise accounts based on counterfactual replay analysis.",
    currentConfiguration: {
      marketingBudget: "₹1.30 Cr",
      workingInventory: "850 units",
      unitPrice: "₹105",
      expectedRevenue: "₹47.5 Cr",
      expectedProfit: "₹19.6 Cr",
      expectedMargin: "33.0%",
    },
    recommendedConfiguration: {
      marketingBudget: "₹1.30 Cr",
      workingInventory: "850 units",
      unitPrice: "₹112",
      expectedRevenue: "₹50.1 Cr",
      expectedProfit: "₹21.5 Cr",
      expectedMargin: "36.2%",
    },
    selectedConfiguration: {
      marketingBudget: "₹1.30 Cr",
      workingInventory: "850 units",
      unitPrice: "₹112",
      expectedRevenue: "₹50.1 Cr",
      expectedProfit: "₹21.5 Cr",
      expectedMargin: "36.2%",
    },
    evidence: [
      {
        id: "ev-p1",
        signal: "Historical Price Tolerance",
        detail: "Counterfactual replay of 2025 renewals showed 98.4% retention under 6-8% indexation.",
        metricImpact: "Profit +₹1.9 Cr",
        confidenceContribution: 26,
        source: "Replay Engine",
        timestamp: "2026-09-28T15:00:00Z",
        type: "price",
      },
    ],
    alternatives: [
      {
        id: "alt-p1",
        name: "6.2% Indexation (Selected)",
        description: "Adjust unit price to ₹112 across mid-tier accounts.",
        marketingBudget: "₹1.30 Cr",
        workingInventory: "850 units",
        unitPrice: "₹112",
        expectedRevenue: "₹50.1 Cr",
        expectedProfit: "₹21.5 Cr",
        expectedMargin: "36.2%",
        constraintsSatisfied: true,
        confidence: 81,
        status: "selected",
      },
    ],
    constraints: [
      {
        id: "c-p1",
        name: "Churn Ceiling",
        rule: "Churn ≤ 3.0%",
        requiredLimit: "3.0%",
        selectedValue: "2.4%",
        status: "satisfied",
        slack: "0.6 pp",
      },
    ],
    humanDecision: {
      decisionMaker: "David Thorne",
      role: "Chief Financial Officer",
      action: "approved",
      decidedAt: "2026-09-29T09:15:00Z",
      reason: "Approved without modification based on clear counterfactual replay proof.",
    },
    expectedOutcome: {
      marketingBudget: "₹1.30 Cr",
      workingInventory: "850 units",
      unitPrice: "₹112",
      expectedRevenue: "₹50.1 Cr",
      expectedProfit: "₹21.5 Cr",
      expectedMargin: "36.2%",
    },
    actualOutcome: {
      status: "achieved",
      recordedAt: "2026-09-29T17:00:00Z",
      explanation: "Captured ₹21.6 Cr gross profit with 36.4% margin and zero churn spike.",
      summary: "Exceeded profit projection by +₹0.1 Cr.",
      metrics: [
        {
          metric: "Gross Profit",
          expected: "₹21.5 Cr",
          actual: "₹21.6 Cr",
          variance: "+₹0.1 Cr (+0.5%)",
          varianceType: "positive",
        },
        {
          metric: "Operating Margin",
          expected: "36.2%",
          actual: "36.4%",
          variance: "+0.2 pp",
          varianceType: "positive",
        },
      ],
    },
    uncertainty: {
      confidence: 81,
      baseCaseProfit: "₹21.5 Cr",
      downsideProfit: "₹20.9 Cr",
      upsideProfit: "₹22.1 Cr",
      revenueRange: "₹49.2 Cr — ₹51.0 Cr",
      grossProfitRange: "₹20.9 Cr — ₹22.1 Cr",
      keyDrivers: ["Renewal cycle scheduling", "Account executive negotiation skill"],
    },
    learning: {
      isAvailable: true,
      whatWeExpected: "6.2% price increase would generate ₹1.9 Cr incremental profit with <0.5% churn delta.",
      whatHappened: "Actual outcome delivered ₹21.6 Cr profit and churn remained at 2.38%.",
      whatWeLearned: "Mid-market accounts accept indexed renewal pricing when tied to product enhancement logs.",
      nextTimeConsideration: "Standardize annual indexation clauses across all mid-tier master service agreements.",
    },
    lineage: [
      {
        stage: "Opportunity",
        id: "OPP-6610",
        status: "completed",
        timestamp: "14:00 UTC",
        route: "/opportunities",
        description: "Yield indexation gap flagged",
      },
      {
        stage: "Decision Replay",
        id: "DEC-2026-PRC-091",
        status: "completed",
        timestamp: "15:10 UTC",
        route: "/replay",
        description: "Counterfactual replay validated",
      },
      {
        stage: "Human Approval",
        id: "DEC-2026-PRC-091",
        status: "completed",
        timestamp: "09:15 UTC",
        route: "/decisions",
        description: "Approved by CFO",
      },
      {
        stage: "Decision DNA",
        id: "DNA-2026-004",
        status: "active",
        timestamp: "17:00 UTC",
        route: "/decision-dna",
        description: "Archived with positive outcome",
      },
    ],
    provenance: {
      dnaId: "DNA-2026-004",
      decisionId: "DEC-2026-PRC-091",
      opportunityId: "OPP-6610",
      investigationId: "INV-2026-022",
      replayId: "DEC-2026-PRC-091",
      scenarioId: "SCN-2026-074",
      optimizationId: "OPT-2026-031",
      verifiedBy: "Governance Engine (SHA-256 Mock Checksum #99f0a2)",
      recordedAt: "2026-09-29T17:00:00Z",
    },
    auditEvents: [
      {
        id: "ae-p1",
        timestamp: "2026-09-28T14:00:00Z",
        time: "14:00 UTC",
        actor: "Finance Engine",
        event: "Opportunity Flagged",
        description: "Yield gap discovered.",
        type: "detected",
      },
    ],
    confidence: 81,
  },
  {
    id: "DNA-2026-005",
    decisionId: "DEC-2026-GEO-022",
    title: "Margin Protection & Regional Expansion Strategy",
    type: "manual",
    status: "rejected",
    createdAt: "2026-09-27T09:00:00Z",
    decisionDate: "2026-09-27T16:12:00Z",
    owner: "Regional Strategy",
    organization: "UrbanCart Retail Dynamics",
    opportunityId: "OPP-5120",
    trigger: {
      problemTitle: "Un-domiciled Regional Sales Expansion Proposal",
      description: "Proposal to hire 8 regional sales reps in Singapore ahead of corporate entity statutory tax clearance.",
      detectedAt: "2026-09-27T08:30:00Z",
      metricAlert: "Statutory Compliance Risk -40%",
      opportunityId: "OPP-5120",
    },
    businessQuestion: "Should we fast-track regional sales hiring prior to local tax domicile approval?",
    summary: "Proposed hiring 8 direct sales reps in Singapore ahead of local entity regulatory compliance. Formally rejected by General Counsel.",
    currentConfiguration: {
      marketingBudget: "₹0.80 Cr",
      workingInventory: "600 units",
      unitPrice: "₹100",
      expectedRevenue: "₹38.0 Cr",
      expectedProfit: "₹16.0 Cr",
      expectedMargin: "28.0%",
    },
    recommendedConfiguration: {
      marketingBudget: "₹1.90 Cr",
      workingInventory: "600 units",
      unitPrice: "₹100",
      expectedRevenue: "₹42.0 Cr",
      expectedProfit: "₹18.0 Cr",
      expectedMargin: "28.5%",
    },
    selectedConfiguration: {
      marketingBudget: "₹0.80 Cr",
      workingInventory: "600 units",
      unitPrice: "₹100",
      expectedRevenue: "₹38.0 Cr",
      expectedProfit: "₹16.0 Cr",
      expectedMargin: "28.0%",
    },
    evidence: [
      {
        id: "ev-g1",
        signal: "Regulatory Compliance Breach",
        detail: "Singapore legal counsel advises substantial penalties for un-domiciled employment contracts.",
        metricImpact: "Legal Risk Critical",
        confidenceContribution: 35,
        source: "General Counsel Legal Brief",
        timestamp: "2026-09-27T11:00:00Z",
        type: "margin",
      },
    ],
    alternatives: [
      {
        id: "alt-g1",
        name: "Fast-Track Direct Hiring",
        description: "Hire 8 reps immediately through third-party agency.",
        marketingBudget: "₹1.90 Cr",
        workingInventory: "600 units",
        unitPrice: "₹100",
        expectedRevenue: "₹42.0 Cr",
        expectedProfit: "₹18.0 Cr",
        expectedMargin: "28.5%",
        constraintsSatisfied: false,
        confidence: 65,
        status: "rejected",
        rejectionReason: "Breached statutory compliance constraint.",
      },
      {
        id: "alt-g2",
        name: "Maintain Current Footprint (Selected)",
        description: "Defer direct hiring until formal corporate entity registration in Q1 2027.",
        marketingBudget: "₹0.80 Cr",
        workingInventory: "600 units",
        unitPrice: "₹100",
        expectedRevenue: "₹38.0 Cr",
        expectedProfit: "₹16.0 Cr",
        expectedMargin: "28.0%",
        constraintsSatisfied: true,
        confidence: 94,
        status: "selected",
      },
    ],
    constraints: [
      {
        id: "c-g1",
        name: "Statutory Legal Compliance",
        rule: "Compliance = 100%",
        requiredLimit: "100%",
        selectedValue: "60%",
        status: "violated",
        slack: "-40% breach",
      },
    ],
    humanDecision: {
      decisionMaker: "Elena Rostova",
      role: "General Counsel",
      action: "rejected",
      decidedAt: "2026-09-27T16:12:00Z",
      reason: "Rejected proposal due to non-compliant tax liability. Entity registration must precede direct payroll execution.",
    },
    expectedOutcome: {
      marketingBudget: "₹0.80 Cr",
      workingInventory: "600 units",
      unitPrice: "₹100",
      expectedRevenue: "₹38.0 Cr",
      expectedProfit: "₹16.0 Cr",
      expectedMargin: "28.0%",
    },
    actualOutcome: {
      status: "achieved",
      recordedAt: "2026-09-28T09:00:00Z",
      explanation: "Maintained baseline operations without statutory penalties or unbudgeted tax liabilities.",
      summary: "Zero regulatory penalties accrued; entity formation progressing for Q1 2027.",
      metrics: [
        {
          metric: "Compliance Rating",
          expected: "100%",
          actual: "100%",
          variance: "0% (Clean)",
          varianceType: "positive",
        },
      ],
    },
    uncertainty: {
      confidence: 65,
      baseCaseProfit: "₹16.0 Cr",
      downsideProfit: "₹14.5 Cr",
      upsideProfit: "₹17.2 Cr",
      revenueRange: "₹36.0 Cr — ₹40.0 Cr",
      grossProfitRange: "₹14.5 Cr — ₹17.2 Cr",
      keyDrivers: ["Singapore entity statutory approval timeline", "Foreign currency hedge rates"],
    },
    learning: {
      isAvailable: true,
      whatWeExpected: "Direct sales would accelerate regional pipeline by 3 quarters.",
      whatHappened: "Legal and tax risks far outweighed the prospective initial revenue lift.",
      whatWeLearned: "Regional corporate entity readiness must be a prerequisite gate before drafting expansion decisions.",
      nextTimeConsideration: "Add automated regulatory entity verification gate to regional opportunity triggers.",
    },
    lineage: [
      {
        stage: "Opportunity",
        id: "OPP-5120",
        status: "completed",
        timestamp: "08:30 UTC",
        route: "/opportunities",
        description: "Expansion proposal drafted",
      },
      {
        stage: "Human Approval",
        id: "DEC-2026-GEO-022",
        status: "completed",
        timestamp: "16:12 UTC",
        route: "/decisions",
        description: "Rejected by General Counsel",
      },
      {
        stage: "Decision DNA",
        id: "DNA-2026-005",
        status: "active",
        timestamp: "09:00 UTC",
        route: "/decision-dna",
        description: "Archived with rejection rationale and learning",
      },
    ],
    provenance: {
      dnaId: "DNA-2026-005",
      decisionId: "DEC-2026-GEO-022",
      opportunityId: "OPP-5120",
      investigationId: "INV-2026-018",
      replayId: "DEC-2026-MKT-002",
      scenarioId: "SCN-2026-061",
      optimizationId: "OPT-2026-015",
      verifiedBy: "Governance Engine (SHA-256 Mock Checksum #33b7a1)",
      recordedAt: "2026-09-28T09:00:00Z",
    },
    auditEvents: [
      {
        id: "ae-g1",
        timestamp: "2026-09-27T08:30:00Z",
        time: "08:30 UTC",
        actor: "Regional Strategy",
        event: "Expansion Proposal Submitted",
        description: "Submitted for executive review.",
        type: "detected",
      },
      {
        id: "ae-g2",
        timestamp: "2026-09-27T16:12:00Z",
        time: "16:12 UTC",
        actor: "Elena Rostova (General Counsel)",
        event: "Proposal Rejected",
        description: "Justification: Regulatory tax non-compliance.",
        type: "authorized",
      },
    ],
    confidence: 65,
  },
];

// Backward compatibility with Phase 1 organizational DNA scaffold
export const MOCK_DECISION_DNA: DecisionDNA = {
  organizationId: "org_global_enterprise",
  organizationName: "UrbanCart Retail Dynamics",
  dnaHealthScore: 88,
  overallRiskTolerance: "growth_oriented",
  governanceComplianceScore: 96,
  traits: [
    {
      name: "Data-Driven Rigor",
      score: 94,
      benchmarkAverage: 71,
      interpretation: "Decisions consistently back-tested against empirical historical series and Monte Carlo confidence intervals.",
    },
    {
      name: "Execution Velocity",
      score: 89,
      benchmarkAverage: 62,
      interpretation: "Stakeholder consensus achieved within 4.2 hours compared to 54 hours industry median.",
    },
    {
      name: "Risk-Hedging Agility",
      score: 82,
      benchmarkAverage: 68,
      interpretation: "Proactive counter-measures integrated prior to committing capital.",
    },
    {
      name: "Cognitive Objectivity",
      score: 86,
      benchmarkAverage: 65,
      interpretation: "Low susceptibility to recency bias or sunk-cost fallacies.",
    },
  ],
  biasProfiles: [
    {
      detectedBias: "status_quo",
      severityLevel: "low",
      affectedDecisionCount: 2,
      remedyRecommendation: "Enforce automated counterfactual replay for all legacy contract rollover reviews.",
    },
    {
      detectedBias: "anchoring",
      severityLevel: "low",
      affectedDecisionCount: 1,
      remedyRecommendation: "Introduce blind independent parameter variance bounds during scenario drafting.",
    },
  ],
  patternClusters: [
    {
      id: "cl_1",
      clusterName: "Algorithmic Fast-Track Repricing",
      frequencyPercentage: 42,
      successRatePercentage: 96.5,
      averageDecisionCycleHours: 2.1,
      keyCharacteristics: ["Automated Elasticity Check", "Multi-Stakeholder Pre-approval", "Instant Telemetry Loop"],
    },
    {
      id: "cl_2",
      clusterName: "Proactive Retention Escalation",
      frequencyPercentage: 33,
      successRatePercentage: 91.2,
      averageDecisionCycleHours: 5.4,
      keyCharacteristics: ["SLA Root Cause Mapping", "Automated Engineering Dispatch", "Executive Visibility"],
    },
  ],
  lastSynthesizedAt: "2026-09-29T10:00:00Z",
};
