import type {
  DecisionItem,
  DecisionSummaryStats,
} from "@/types/decision-registry";

export const MOCK_DECISION_SUMMARY_STATS: DecisionSummaryStats = {
  total: 31,
  pending: 4,
  approved: 18,
  modified: 6,
  rejected: 3,
  lastUpdated: "Today, 14:48 UTC",
};

export const MOCK_DECISION_REGISTRY_ITEMS: DecisionItem[] = [
  {
    id: "dec-mkt-018",
    code: "DEC-2026-MKT-018",
    title: "Marketing Allocation Optimization",
    source: "optimization",
    objective: "Maximize Gross Profit",
    impact: "₹2.8 Cr",
    impactNum: 28000000,
    confidence: 84,
    status: "under_review",
    priority: "critical",
    owner: "Alexandra Chen",
    createdAt: "2026-09-29T14:32:00Z",
    updatedAt: "2026-09-29T14:35:00Z",
    summary:
      "Pareto-optimal shift increasing performance marketing spend while scaling unit price to capture ₹22.4 Cr total gross profit under strict churn constraints.",
    recommendation: {
      variables: {
        marketingBudget: "₹1.65 Cr",
        workingInventory: "1,050 units",
        unitPrice: "₹108",
      },
      projectedOutcomes: {
        grossProfit: "₹22.4 Cr",
        revenue: "₹53.1 Cr",
        operatingMargin: "34.6%",
      },
      constraintsSatisfied: true,
      statusNote: "All configured hard constraints are satisfied.",
    },
    comparisons: [
      {
        metric: "Marketing Budget",
        current: "₹1.40 Cr",
        recommended: "₹1.65 Cr",
        change: "+₹0.25 Cr",
        changeType: "positive",
      },
      {
        metric: "Inventory",
        current: "900 units",
        recommended: "1,050 units",
        change: "+150 units",
        changeType: "positive",
      },
      {
        metric: "Unit Price",
        current: "₹105",
        recommended: "₹108",
        change: "+₹3",
        changeType: "positive",
      },
      {
        metric: "Gross Profit",
        current: "₹19.6 Cr",
        recommended: "₹22.4 Cr",
        change: "+₹2.8 Cr",
        changeType: "positive",
      },
      {
        metric: "Revenue",
        current: "₹48.2 Cr",
        recommended: "₹53.1 Cr",
        change: "+₹4.9 Cr",
        changeType: "positive",
      },
      {
        metric: "Operating Margin",
        current: "32.4%",
        recommended: "34.6%",
        change: "+2.2 pp",
        changeType: "positive",
      },
    ],
    constraints: [
      {
        id: "c-budget",
        name: "Marketing Budget Ceiling",
        limit: "₹2.00 Cr",
        recommended: "₹1.65 Cr",
        slack: "₹0.35 Cr",
        status: "satisfied",
      },
      {
        id: "c-margin",
        name: "Minimum Operating Margin",
        limit: "25.0%",
        recommended: "34.6%",
        slack: "9.6 pp",
        status: "satisfied",
      },
      {
        id: "c-inventory",
        name: "Working Inventory Limit",
        limit: "1,500 units",
        recommended: "1,050 units",
        slack: "450 units",
        status: "satisfied",
      },
      {
        id: "c-churn",
        name: "Annual Customer Churn",
        limit: "3.5%",
        recommended: "3.1%",
        slack: "0.4 pp",
        status: "satisfied",
      },
    ],
    evidence: [
      {
        title: "Revenue efficiency",
        signal: "Strong positive signal",
        detail: "Elasticity modeling shows incremental spend yields 3.8x marginal return.",
        type: "efficiency",
      },
      {
        title: "Operating margin",
        signal: "Above configured minimum",
        detail: "34.6% projected margin provides comfortable 9.6 pp buffer above threshold.",
        type: "margin",
      },
      {
        title: "Marketing efficiency",
        signal: "High sensitivity",
        detail: "Driver ranking score 9.2/10 confirms marketing budget as the primary leverage point.",
        type: "sensitivity",
      },
      {
        title: "Inventory",
        signal: "Within hard constraint",
        detail: "1,050 units allows 98.2% service level with 450 units buffer before warehouse capacity limit.",
        type: "inventory",
      },
      {
        title: "Price",
        signal: "Positive projected contribution",
        detail: "Modest ₹3 price bump maintains transaction volume while lifting basket contribution.",
        type: "price",
      },
    ],
    confidenceDetails: {
      score: 84,
      highConfidenceSignals: 7,
      supportingEvidence: 16,
      constraintsVerified: 4,
      totalConstraints: 4,
      explanation:
        "Confidence reflects the completeness and consistency of the inputs available to this mock decision workspace.",
      projectedProfitRange: "₹21.7 Cr — ₹23.0 Cr",
      projectedRevenueRange: "₹51.9 Cr — ₹54.2 Cr",
      uncertaintyExplanation:
        "Projected ranges represent uncertainty in the mock optimization workspace and should be reviewed before approval.",
    },
    auditTimeline: [
      {
        id: "aud-1",
        time: "14:32",
        timestamp: "2026-09-29T14:32:00Z",
        event: "Recommendation generated by Constraint-Aware Optimizer",
        actor: "Optimizer (OPT-2026-042)",
        type: "generated",
      },
      {
        id: "aud-2",
        time: "14:35",
        timestamp: "2026-09-29T14:35:00Z",
        event: "Decision opened for executive review",
        actor: "Alexandra Chen",
        type: "review",
      },
      {
        id: "aud-3",
        time: "14:41",
        timestamp: "2026-09-29T14:41:00Z",
        event: "Evidence & driver elasticity signals reviewed",
        actor: "Alexandra Chen",
        type: "evidence",
      },
      {
        id: "aud-4",
        time: "14:45",
        timestamp: "2026-09-29T14:45:00Z",
        event: "All 4 business constraints verified and satisfied",
        actor: "Governance Engine",
        type: "constraint",
      },
    ],
    provenance: {
      opportunityId: "OPP-9021",
      investigationId: "INV-2026-044",
      replayId: "DEC-2026-MKT-018",
      scenarioId: "SCN-2026-081",
      optimizerId: "OPT-2026-042",
    },
  },
  {
    id: "dec-scm-044",
    code: "DEC-2026-SCM-044",
    title: "Inventory Rebalancing Across North Hubs",
    source: "scenario",
    objective: "Minimize Stockouts",
    impact: "₹1.4 Cr",
    impactNum: 14000000,
    confidence: 78,
    status: "proposed",
    priority: "high",
    owner: "Operations Team",
    createdAt: "2026-09-29T11:40:00Z",
    updatedAt: "2026-09-29T12:20:00Z",
    summary:
      "Shift 350 buffer units from Mumbai central depot to Delhi North hub to eliminate regional delivery delays.",
    recommendation: {
      variables: {
        marketingBudget: "₹1.10 Cr",
        workingInventory: "1,250 units",
        unitPrice: "₹105",
      },
      projectedOutcomes: {
        grossProfit: "₹20.1 Cr",
        revenue: "₹49.8 Cr",
        operatingMargin: "33.1%",
      },
      constraintsSatisfied: true,
      statusNote: "Regional logistics threshold satisfied.",
    },
    comparisons: [
      {
        metric: "Working Inventory",
        current: "900 units",
        recommended: "1,250 units",
        change: "+350 units",
        changeType: "positive",
      },
      {
        metric: "Gross Profit",
        current: "₹18.7 Cr",
        recommended: "₹20.1 Cr",
        change: "+₹1.4 Cr",
        changeType: "positive",
      },
      {
        metric: "Revenue",
        current: "₹47.0 Cr",
        recommended: "₹49.8 Cr",
        change: "+₹2.8 Cr",
        changeType: "positive",
      },
    ],
    constraints: [
      {
        id: "c-sc-1",
        name: "Logistics Budget",
        limit: "₹1.50 Cr",
        recommended: "₹1.10 Cr",
        slack: "₹0.40 Cr",
        status: "satisfied",
      },
      {
        id: "c-sc-2",
        name: "Max Transit SLA",
        limit: "48 hours",
        recommended: "24 hours",
        slack: "24 hours",
        status: "satisfied",
      },
    ],
    evidence: [
      {
        title: "Fulfillment Velocity",
        signal: "Positive trend",
        detail: "Northern regional stockout rate drops from 8.2% to 1.1%.",
        type: "inventory",
      },
      {
        title: "Margin stability",
        signal: "Nominal cost increase",
        detail: "Inter-state freight cost balanced by reduced backorder penalties.",
        type: "margin",
      },
    ],
    confidenceDetails: {
      score: 78,
      highConfidenceSignals: 5,
      supportingEvidence: 11,
      constraintsVerified: 2,
      totalConstraints: 2,
      explanation:
        "Based on 6-month logistics data across 3 carrier integrations.",
      projectedProfitRange: "₹19.5 Cr — ₹20.6 Cr",
      projectedRevenueRange: "₹48.9 Cr — ₹50.7 Cr",
      uncertaintyExplanation:
        "Subject to fuel surcharge volatility in northern transit routes.",
    },
    auditTimeline: [
      {
        id: "aud-scm-1",
        time: "11:40",
        timestamp: "2026-09-29T11:40:00Z",
        event: "Scenario simulation completed in Scenario Lab",
        actor: "Scenario Lab (SCN-2026-088)",
        type: "generated",
      },
      {
        id: "aud-scm-2",
        time: "12:20",
        timestamp: "2026-09-29T12:20:00Z",
        event: "Queued for operations sign-off",
        actor: "System",
        type: "review",
      },
    ],
    provenance: {
      opportunityId: "OPP-7412",
      investigationId: "INV-2026-031",
      replayId: "DEC-2026-LOG-009",
      scenarioId: "SCN-2026-088",
      optimizerId: "OPT-2026-039",
    },
  },
  {
    id: "dec-prc-091",
    code: "DEC-2026-PRC-091",
    title: "Mid-Tier Dynamic Pricing Adjustment",
    source: "replay",
    objective: "Maximize Operating Margin",
    impact: "₹1.9 Cr",
    impactNum: 19000000,
    confidence: 81,
    status: "approved",
    priority: "medium",
    owner: "Finance & Monetization",
    createdAt: "2026-09-28T15:10:00Z",
    updatedAt: "2026-09-29T09:15:00Z",
    summary:
      "Enacted 6.2% price adjustment across Tier-2 SaaS enterprise accounts based on counterfactual replay analysis.",
    recommendation: {
      variables: {
        marketingBudget: "₹1.30 Cr",
        workingInventory: "850 units",
        unitPrice: "₹112",
      },
      projectedOutcomes: {
        grossProfit: "₹21.5 Cr",
        revenue: "₹50.1 Cr",
        operatingMargin: "36.2%",
      },
      constraintsSatisfied: true,
      statusNote: "Approved without modifications by CFO office.",
    },
    comparisons: [
      {
        metric: "Unit Price",
        current: "₹105",
        recommended: "₹112",
        change: "+₹7",
        changeType: "positive",
      },
      {
        metric: "Operating Margin",
        current: "33.0%",
        recommended: "36.2%",
        change: "+3.2 pp",
        changeType: "positive",
      },
      {
        metric: "Gross Profit",
        current: "₹19.6 Cr",
        recommended: "₹21.5 Cr",
        change: "+₹1.9 Cr",
        changeType: "positive",
      },
    ],
    constraints: [
      {
        id: "c-prc-1",
        name: "Contract Churn Ceiling",
        limit: "3.0%",
        recommended: "2.4%",
        slack: "0.6 pp",
        status: "satisfied",
      },
    ],
    evidence: [
      {
        title: "Replay Counterfactual",
        signal: "Historical match",
        detail: "Demonstrated resilience against competitor discounting in Q2 2025 replay.",
        type: "price",
      },
    ],
    confidenceDetails: {
      score: 81,
      highConfidenceSignals: 6,
      supportingEvidence: 14,
      constraintsVerified: 1,
      totalConstraints: 1,
      explanation:
        "High historical correlation with low customer price sensitivity.",
      projectedProfitRange: "₹20.9 Cr — ₹22.1 Cr",
      projectedRevenueRange: "₹49.2 Cr — ₹51.0 Cr",
      uncertaintyExplanation: "Standard contract renewal timing window.",
    },
    auditTimeline: [
      {
        id: "aud-p-1",
        time: "15:10",
        timestamp: "2026-09-28T15:10:00Z",
        event: "Replay simulation completed",
        actor: "Replay Engine",
        type: "generated",
      },
      {
        id: "aud-p-2",
        time: "09:15",
        timestamp: "2026-09-29T09:15:00Z",
        event: "Decision approved without modifications",
        actor: "David Thorne (CFO)",
        type: "approved",
      },
    ],
    provenance: {
      opportunityId: "OPP-8802",
      investigationId: "INV-2026-022",
      replayId: "DEC-2026-PRC-091",
      scenarioId: "SCN-2026-074",
      optimizerId: "OPT-2026-031",
    },
  },
  {
    id: "dec-exp-105",
    code: "DEC-2026-EXP-105",
    title: "Enterprise AI Compute Tier Expansion",
    source: "investigation",
    objective: "Prevent Enterprise SLA Penalties",
    impact: "₹3.2 Cr",
    impactNum: 32000000,
    confidence: 88,
    status: "modified",
    priority: "critical",
    owner: "Engineering Leadership",
    createdAt: "2026-09-28T11:00:00Z",
    updatedAt: "2026-09-28T16:20:00Z",
    summary:
      "Provisioning dedicated GPU cluster partitions for Top 20 fintech accounts. Human modified budget from ₹2.2 Cr to ₹1.85 Cr.",
    modifiedConfig: {
      marketingBudget: "₹1.85 Cr",
      workingInventory: "950 units",
      unitPrice: "₹110",
      modifiedAt: "2026-09-28T16:20:00Z",
      modifiedBy: "Marcus Vance",
      notes: "Scaled down hardware allocation to fit revised Q3 capex envelope.",
    },
    recommendation: {
      variables: {
        marketingBudget: "₹2.20 Cr",
        workingInventory: "950 units",
        unitPrice: "₹110",
      },
      projectedOutcomes: {
        grossProfit: "₹24.0 Cr",
        revenue: "₹58.5 Cr",
        operatingMargin: "35.8%",
      },
      constraintsSatisfied: true,
      statusNote: "Approved with modified marketing budget cap.",
    },
    comparisons: [
      {
        metric: "Hardware Budget",
        current: "₹1.50 Cr",
        recommended: "₹2.20 Cr",
        change: "+₹0.70 Cr",
        changeType: "neutral",
      },
      {
        metric: "Gross Profit",
        current: "₹20.8 Cr",
        recommended: "₹24.0 Cr",
        change: "+₹3.2 Cr",
        changeType: "positive",
      },
    ],
    constraints: [
      {
        id: "c-exp-1",
        name: "P99 SLA Guarantee",
        limit: "150ms",
        recommended: "82ms",
        slack: "68ms",
        status: "satisfied",
      },
    ],
    evidence: [
      {
        title: "Root cause diagnosis",
        signal: "Definitive causality",
        detail: "Investigation identified gateway queue congestion as root cause of latency.",
        type: "efficiency",
      },
    ],
    confidenceDetails: {
      score: 88,
      highConfidenceSignals: 8,
      supportingEvidence: 19,
      constraintsVerified: 1,
      totalConstraints: 1,
      explanation: "Direct APM telemetry verification with 99.8% precision.",
      projectedProfitRange: "₹23.1 Cr — ₹24.8 Cr",
      projectedRevenueRange: "₹57.0 Cr — ₹59.8 Cr",
      uncertaintyExplanation: "Low hardware delivery lead time variance.",
    },
    auditTimeline: [
      {
        id: "aud-e-1",
        time: "11:00",
        timestamp: "2026-09-28T11:00:00Z",
        event: "Investigation findings submitted",
        actor: "Investigation Engine (INV-2026-044)",
        type: "generated",
      },
      {
        id: "aud-e-2",
        time: "16:20",
        timestamp: "2026-09-28T16:20:00Z",
        event: "Human modified configuration approved (Cap adjusted to ₹1.85 Cr)",
        actor: "Marcus Vance",
        type: "modified",
      },
    ],
    provenance: {
      opportunityId: "OPP-9021",
      investigationId: "INV-2026-044",
      replayId: "DEC-2026-0043",
      scenarioId: "SCN-2026-081",
      optimizerId: "OPT-2026-042",
    },
  },
  {
    id: "dec-geo-022",
    code: "DEC-2026-GEO-022",
    title: "APAC Early Direct Sales Expansion",
    source: "manual",
    objective: "Capture APAC Enterprise Share",
    impact: "₹2.1 Cr",
    impactNum: 21000000,
    confidence: 65,
    status: "rejected",
    priority: "low",
    owner: "Regional Strategy",
    createdAt: "2026-09-27T09:00:00Z",
    updatedAt: "2026-09-27T16:12:00Z",
    summary:
      "Proposed hiring 8 direct sales reps in Singapore ahead of local entity regulatory compliance.",
    rejectionDetails: {
      reason: "Operational constraints",
      notes: "Regulatory entity formation delayed to Q1 2027. Direct hiring premature without statutory tax clearance.",
      rejectedAt: "2026-09-27T16:12:00Z",
      rejectedBy: "Elena Rostova (General Counsel)",
    },
    recommendation: {
      variables: {
        marketingBudget: "₹1.90 Cr",
        workingInventory: "600 units",
        unitPrice: "₹100",
      },
      projectedOutcomes: {
        grossProfit: "₹18.0 Cr",
        revenue: "₹42.0 Cr",
        operatingMargin: "28.5%",
      },
      constraintsSatisfied: false,
      statusNote: "Rejected due to regulatory constraint failure.",
    },
    comparisons: [
      {
        metric: "Marketing & Sales",
        current: "₹0.80 Cr",
        recommended: "₹1.90 Cr",
        change: "+₹1.10 Cr",
        changeType: "negative",
      },
    ],
    constraints: [
      {
        id: "c-geo-1",
        name: "Statutory Compliance",
        limit: "100%",
        recommended: "60%",
        slack: "-40%",
        status: "violated",
      },
    ],
    evidence: [
      {
        title: "Compliance risk",
        signal: "High negative impact",
        detail: "Singapore legal counsel advises against un-domiciled payroll.",
        type: "margin",
      },
    ],
    confidenceDetails: {
      score: 65,
      highConfidenceSignals: 3,
      supportingEvidence: 6,
      constraintsVerified: 0,
      totalConstraints: 1,
      explanation: "Low confidence due to evolving tax requirements.",
      projectedProfitRange: "₹16.5 Cr — ₹19.2 Cr",
      projectedRevenueRange: "₹39.0 Cr — ₹44.5 Cr",
      uncertaintyExplanation: "High regulatory volatility.",
    },
    auditTimeline: [
      {
        id: "aud-g-1",
        time: "09:00",
        timestamp: "2026-09-27T09:00:00Z",
        event: "Manual proposal created",
        actor: "Regional Sales Lead",
        type: "generated",
      },
      {
        id: "aud-g-2",
        time: "16:12",
        timestamp: "2026-09-27T16:12:00Z",
        event: "Decision rejected with reason: Operational constraints",
        actor: "Elena Rostova (General Counsel)",
        type: "rejected",
      },
    ],
    provenance: {
      opportunityId: "OPP-6610",
      investigationId: "INV-2026-018",
      replayId: "DEC-2026-MKT-002",
      scenarioId: "SCN-2026-061",
      optimizerId: "OPT-2026-015",
    },
  },
  {
    id: "dec-ret-077",
    code: "DEC-2026-RET-077",
    title: "Contract Retention Re-indexation Protocol",
    source: "optimization",
    objective: "Stabilize Multi-Year ARR",
    impact: "₹3.6 Cr",
    impactNum: 36000000,
    confidence: 91,
    status: "recorded",
    priority: "critical",
    owner: "Customer Success & Revenue Ops",
    createdAt: "2026-09-26T10:00:00Z",
    updatedAt: "2026-09-26T17:30:00Z",
    summary:
      "Fully executed and recorded decision stabilizing multi-year renewal commitments with 98.6% customer retention.",
    recommendation: {
      variables: {
        marketingBudget: "₹1.50 Cr",
        workingInventory: "1,000 units",
        unitPrice: "₹106",
      },
      projectedOutcomes: {
        grossProfit: "₹23.8 Cr",
        revenue: "₹55.4 Cr",
        operatingMargin: "35.1%",
      },
      constraintsSatisfied: true,
      statusNote: "Immutable record stored in decision registry.",
    },
    comparisons: [
      {
        metric: "Gross Profit",
        current: "₹20.2 Cr",
        recommended: "₹23.8 Cr",
        change: "+₹3.6 Cr",
        changeType: "positive",
      },
    ],
    constraints: [
      {
        id: "c-ret-1",
        name: "Max Retention Discount",
        limit: "10.0%",
        recommended: "4.5%",
        slack: "5.5 pp",
        status: "satisfied",
      },
    ],
    evidence: [
      {
        title: "ARR Cohort Stability",
        signal: "Historical verification",
        detail: "Recorded outcome matches predicted trajectory within 1.2% error margin.",
        type: "efficiency",
      },
    ],
    confidenceDetails: {
      score: 91,
      highConfidenceSignals: 9,
      supportingEvidence: 24,
      constraintsVerified: 1,
      totalConstraints: 1,
      explanation: "Post-execution audit complete and validated.",
      projectedProfitRange: "₹23.4 Cr — ₹24.2 Cr",
      projectedRevenueRange: "₹54.8 Cr — ₹56.0 Cr",
      uncertaintyExplanation: "Resolved via execution.",
    },
    auditTimeline: [
      {
        id: "aud-r-1",
        time: "10:00",
        timestamp: "2026-09-26T10:00:00Z",
        event: "Decision generated and proposed",
        actor: "DecisionOS",
        type: "generated",
      },
      {
        id: "aud-r-2",
        time: "17:30",
        timestamp: "2026-09-26T17:30:00Z",
        event: "Final outcome recorded in registry",
        actor: "Alexandra Chen",
        type: "recorded",
      },
    ],
    provenance: {
      opportunityId: "OPP-9021",
      investigationId: "INV-2026-044",
      replayId: "DEC-2026-MKT-018",
      scenarioId: "SCN-2026-081",
      optimizerId: "OPT-2026-042",
    },
  },
];
