import { Opportunity } from "@/types/opportunity";

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp_1",
    code: "OPP-9021",
    title: "Revenue Efficiency Decline in Mid-Market SaaS",
    summary: "Conversion rate dropped 8.2% and CAC increased 14.1% across Tier-2 marketing channels over the last 60 days.",
    category: "pricing_optimization",
    urgency: "critical",
    status: "in_investigation",
    impact: {
      projectedRevenue: 28000000, // ₹2.8 Cr
      costReduction: 6000000,
      netValue: 28000000,
      confidenceScore: 91,
      timeToRealizationDays: 14,
    },
    affectedSegments: ["Mid-Market Tier-2", "Paid Search & Display", "Direct Sales"],
    detectedAt: "2026-09-29T07:20:00Z",
    expiresAt: "2026-10-06T00:00:00Z",
    ownerId: "usr_99182a",
    ownerName: "Alexandra Chen",
    tags: ["High Impact", "Margin Leak", "Needs Investigation"],
  },
  {
    id: "opp_2",
    code: "OPP-9023",
    title: "Regional Inventory Buffer Imbalance Across Western Hubs",
    summary: "Rebalancing regional safety stock thresholds across 3 distribution facilities frees up trapped working capital without stockout risk.",
    category: "supply_chain",
    urgency: "medium",
    status: "detected",
    impact: {
      projectedRevenue: 0,
      costReduction: 8400000, // ₹84 L
      netValue: 8400000,
      confidenceScore: 87,
      timeToRealizationDays: 30,
    },
    affectedSegments: ["Logistics", "Western US Warehouses", "Express Fulfillment"],
    detectedAt: "2026-09-28T16:00:00Z",
    expiresAt: "2026-10-20T00:00:00Z",
    ownerName: "Logistics Dispatch",
    tags: ["Working Capital", "Supply Chain", "Optimization Ready"],
  },
  {
    id: "opp_3",
    code: "OPP-9022",
    title: "Healthcare B2B Contract Churn Intervention",
    summary: "Behavioral telemetry shows 34 enterprise healthcare accounts with declining API invocation frequency and high renewal risk.",
    category: "churn_prevention",
    urgency: "high",
    status: "decision_ready",
    impact: {
      projectedRevenue: 19700000, // ₹1.97 Cr
      costReduction: 1200000,
      netValue: 19700000,
      confidenceScore: 88,
      timeToRealizationDays: 21,
    },
    affectedSegments: ["Healthcare Verticals", "Legacy API Integrations"],
    detectedAt: "2026-09-28T14:10:00Z",
    expiresAt: "2026-10-15T00:00:00Z",
    ownerId: "usr_48211b",
    ownerName: "Marcus Vance",
    tags: ["Retention", "Executive Sign-Off", "Customer Success"],
  },
  {
    id: "opp_4",
    code: "OPP-9025",
    title: "Fintech Cross-Sell Dynamic Pricing Leverage",
    summary: "Algorithmic propensity models indicate high willingness-to-pay for real-time risk scoring add-ons among Tier-1 banking clients.",
    category: "cross_sell",
    urgency: "low",
    status: "detected",
    impact: {
      projectedRevenue: 4500000, // ₹45 L
      costReduction: 0,
      netValue: 4500000,
      confidenceScore: 82,
      timeToRealizationDays: 45,
    },
    affectedSegments: ["Fintech & Banking", "Risk API Clients"],
    detectedAt: "2026-09-27T11:00:00Z",
    expiresAt: "2026-10-30T00:00:00Z",
    ownerName: "Commercial Growth",
    tags: ["Cross-Sell", "Revenue Expansion"],
  },
];
