import { OptimizationResult } from "@/types/optimizer";

export const MOCK_OPTIMIZATION_RESULT: OptimizationResult = {
  id: "opt_7720",
  optimizerRunCode: "OPT-2026-CAPEX-V4",
  objective: "maximize_profit",
  status: "optimal",
  targetMetricProjectedLift: 14.8,
  baselineObjectiveValue: 24500000,
  optimizedObjectiveValue: 28120000,
  constraints: [
    {
      id: "c_1",
      name: "Max Customer Churn Ceiling",
      metricKey: "churn_rate_pct",
      operator: "lte",
      targetValue: 3.5,
      isHardConstraint: true,
      status: "binding",
    },
    {
      id: "c_2",
      name: "Minimum CAC Payback Velocity",
      metricKey: "cac_payback_months",
      operator: "lte",
      targetValue: 12.0,
      isHardConstraint: true,
      status: "satisfied",
    },
    {
      id: "c_3",
      name: "Working Capital Reserve Floor",
      metricKey: "min_cash_reserve_usd",
      operator: "gte",
      targetValue: 15000000,
      isHardConstraint: true,
      status: "satisfied",
    },
  ],
  allocations: [
    {
      id: "all_1",
      segmentName: "Enterprise Tier-1 AI Solutions",
      currentAllocation: 8500000,
      optimizedAllocation: 12400000,
      recommendedDelta: 3900000,
      expectedContribution: 2100000,
    },
    {
      id: "all_2",
      segmentName: "Mid-Market Autonomous Agents",
      currentAllocation: 6000000,
      optimizedAllocation: 7800000,
      recommendedDelta: 1800000,
      expectedContribution: 1120000,
    },
    {
      id: "all_3",
      segmentName: "Legacy On-Premise Support",
      currentAllocation: 10000000,
      optimizedAllocation: 4300000,
      recommendedDelta: -5700000,
      expectedContribution: 400000,
    },
  ],
  solverTimeMs: 842,
  iterationsCount: 14850,
  createdAt: "2026-09-29T09:15:00Z",
};
