import {
  HistoricalDecisionOption,
  ReplayWorkspaceData,
} from "@/types/replay-workspace";

export const MOCK_HISTORICAL_DECISIONS: HistoricalDecisionOption[] = [
  {
    id: "hist_dec_01",
    code: "DEC-2026-MKT-018",
    title: "Q2 Marketing Allocation",
    date: "15 June 2026",
    actionTaken: "Increase paid marketing allocation by 18%",
    owner: "Chief Marketing Officer",
    approvers: ["Chief Financial Officer", "Chief Sales & Operating Officer"],
    constraint: "Marketing budget ≤ ₹2 Cr",
    reason: "Revenue growth was slowing in Tier-2 channels.",
    status: "Executed & Audited",
    availableBranches: [
      {
        id: "branch_reallocate",
        label: "Reallocate Marketing (Optimal Alternative)",
        description: "Reallocate spend from broad Tier-2 campaigns into high-converting organic & account-based tracks.",
      },
      {
        id: "branch_status_quo",
        label: "Status Quo (No Budget Increase)",
        description: "Maintain baseline allocation without the 18% capital injection.",
      },
      {
        id: "branch_reduce_spend",
        label: "Reduce Campaign Spend (−10%)",
        description: "Cut underperforming paid search bids and protect cash buffer.",
      },
      {
        id: "branch_high_conv",
        label: "Increase High-Conversion Channels (+25%)",
        description: "Concentrate budget purely on Tier-1 enterprise inbound intent.",
      },
    ],
  },
  {
    id: "hist_dec_02",
    code: "DEC-2026-SCM-044",
    title: "Inventory Rebalancing",
    date: "02 May 2026",
    actionTaken: "Increase Tier-2 inventory allocation",
    owner: "VP Global Supply Chain",
    approvers: ["Chief Operating Officer", "VP Procurement"],
    constraint: "Holding cost variance ≤ 4%",
    reason: "Buffer against regional stockouts during carrier contract renegotiation.",
    status: "Executed & Audited",
    availableBranches: [
      {
        id: "branch_rebalance_dynamic",
        label: "Dynamic Buffer Sharing (Optimal Alternative)",
        description: "Distribute safety stock across 3 regional transit hubs with cross-docking.",
      },
      {
        id: "branch_rebalance_flat",
        label: "Flat Centralized Warehouse Retention",
        description: "Keep all inventory centralized in Western regional hub.",
      },
      {
        id: "branch_just_in_time",
        label: "Just-In-Time Supplier Sourcing",
        description: "Transition Tier-2 items to direct dropship fulfillment.",
      },
    ],
  },
  {
    id: "hist_dec_03",
    code: "DEC-2026-PRC-091",
    title: "Pricing Adjustment",
    date: "18 April 2026",
    actionTaken: "Reduce selected product pricing by 5%",
    owner: "Head of Commercial Strategy",
    approvers: ["Chief Revenue Officer", "Head of Finance"],
    constraint: "Contribution margin ≥ 28%",
    reason: "Counteract aggressive discounting by competitors in Mid-Market segment.",
    status: "Executed & Audited",
    availableBranches: [
      {
        id: "branch_price_bundle",
        label: "Feature Bundling (Optimal Alternative)",
        description: "Retain list price but include 6 months of premium telemetry support.",
      },
      {
        id: "branch_price_discount",
        label: "Direct 5% Discount Across Tier-2",
        description: "Price drop across entire catalog for all renewing accounts.",
      },
      {
        id: "branch_tiered_commitment",
        label: "Multi-Year Tiered Rebate",
        description: "Discount only on 24-month or longer contract extensions.",
      },
    ],
  },
];

export const MOCK_REPLAY_WORKSPACES: Record<string, ReplayWorkspaceData> = {
  hist_dec_01: {
    decision: MOCK_HISTORICAL_DECISIONS[0],
    selectedBranchId: "branch_reallocate",
    decisionPoint: {
      date: "15 June 2026",
      title: "Q2 Marketing Allocation Decision Point",
      originalAction: "Increase paid marketing allocation by 18%",
      description:
        "Leadership authorized an 18% increase in paid acquisition budget to reignite slowing Tier-2 revenue. At this critical fork, alternative allocation strategies were available.",
    },
    actualTimeline: [
      {
        id: "act_w1",
        periodLabel: "Week 1",
        date: "22 June 2026",
        eventTitle: "Campaign launched across Tier-2",
        explanation: "Initial ad spend surge without creative refresh caused immediate CPA spike across paid search.",
        metricChanges: [
          { label: "Conversion", value: "−3.2%", direction: "negative" },
          { label: "CAC", value: "+5.1%", direction: "negative" },
        ],
        statusVariant: "warning",
      },
      {
        id: "act_w2",
        periodLabel: "Week 2",
        date: "29 June 2026",
        eventTitle: "Channel efficiency diverged",
        explanation: "Tier-2 paid display traffic volume saturated, triggering intense competitor keyword bidding.",
        metricChanges: [
          { label: "Conversion", value: "−6.4%", direction: "negative" },
          { label: "CAC", value: "+9.2%", direction: "negative" },
        ],
        statusVariant: "critical",
      },
      {
        id: "act_w4",
        periodLabel: "Week 4",
        date: "13 July 2026",
        eventTitle: "Revenue outcome realized",
        explanation: "Quarter concluded with top-line gains eroded by disproportionate acquisition cost overruns.",
        metricChanges: [
          { label: "Revenue", value: "+4.0%", direction: "positive" },
          { label: "Profit", value: "+2.0%", direction: "neutral" },
        ],
        statusVariant: "neutral",
      },
    ],
    counterfactualTimeline: [
      {
        id: "cf_w1",
        periodLabel: "Week 1",
        date: "22 June 2026",
        eventTitle: "High-intent channel reallocation",
        explanation: "Redirected 60% of increment into high-intent inbound search while capping underperforming channels.",
        metricChanges: [
          { label: "Conversion", value: "+1.2%", direction: "positive" },
          { label: "CAC", value: "Stable", direction: "neutral" },
        ],
        statusVariant: "positive",
      },
      {
        id: "cf_w2",
        periodLabel: "Week 2",
        date: "29 June 2026",
        eventTitle: "Account-based targeting scaled",
        explanation: "Dynamic frequency capping prevented impression waste; sales outreach synchronized with ad engagement.",
        metricChanges: [
          { label: "Conversion", value: "+3.1%", direction: "positive" },
          { label: "CAC", value: "−2.0%", direction: "positive" },
        ],
        statusVariant: "positive",
      },
      {
        id: "cf_w4",
        periodLabel: "Week 4",
        date: "13 July 2026",
        eventTitle: "Optimal outcome realized",
        explanation: "Revenue expanded across higher-margin enterprise contracts with minimal marginal cost.",
        metricChanges: [
          { label: "Revenue", value: "+8.0%", direction: "positive" },
          { label: "Profit", value: "+11.0%", direction: "positive" },
        ],
        statusVariant: "positive",
      },
    ],
    metrics: [
      {
        key: "revenue",
        label: "Revenue",
        actualValue: "₹48.2 Cr",
        counterfactualValue: "₹51.0 Cr",
        delta: "+₹2.8 Cr",
        deltaType: "positive",
        actualNum: 48.2,
        counterfactualNum: 51.0,
        unit: "₹ Cr",
        explanation: "Incremental top-line captured via higher-converting mid-market accounts.",
      },
      {
        key: "gross_profit",
        label: "Gross Profit",
        actualValue: "₹19.6 Cr",
        counterfactualValue: "₹22.1 Cr",
        delta: "+₹2.5 Cr",
        deltaType: "positive",
        actualNum: 19.6,
        counterfactualNum: 22.1,
        unit: "₹ Cr",
        explanation: "Lower blended CAC directly flowed into gross enterprise margin.",
      },
      {
        key: "operating_margin",
        label: "Operating Margin",
        actualValue: "32.4%",
        counterfactualValue: "34.1%",
        delta: "+1.7 pp",
        deltaType: "positive",
        actualNum: 32.4,
        counterfactualNum: 34.1,
        unit: "%",
        explanation: "170 bps expansion exceeding company annual guidance targets.",
      },
      {
        key: "orders",
        label: "Orders",
        actualValue: "14,820",
        counterfactualValue: "15,960",
        delta: "+1,140",
        deltaType: "positive",
        actualNum: 14820,
        counterfactualNum: 15960,
        unit: "Orders",
        explanation: "Higher quality leads improved sales qualification velocity by 18%.",
      },
      {
        key: "inventory",
        label: "Inventory Trapped",
        actualValue: "₹6.4 Cr",
        counterfactualValue: "₹5.8 Cr",
        delta: "−₹0.6 Cr",
        deltaType: "positive",
        actualNum: 6.4,
        counterfactualNum: 5.8,
        unit: "₹ Cr",
        explanation: "Faster stock turnover freed working capital from regional fulfillment hubs.",
      },
    ],
    insight: {
      headline: "Counterfactual Insight",
      summary:
        "Under the alternative allocation strategy, the business would have achieved higher revenue and profit while maintaining the required margin constraint.",
      revenueDiff: "+₹2.8 Cr",
      profitDiff: "+₹2.5 Cr",
      marginDiff: "+1.7 pp",
      whatChangedExplanation:
        "The counterfactual branch reduced low-efficiency campaign allocation and redirected budget toward higher-conversion channels with established unit economics.",
    },
    evidence: {
      supportingSignals: [
        "Tier-2 conversion improved from 2.4% baseline to 3.8% under targeted channel routing.",
        "Customer acquisition cost (CAC) remained stable within ±1.5% of seasonal target.",
        "Higher-conversion channels received additional allocation without diminishing returns penalty.",
      ],
      constraintsPreserved: [
        "Budget ceiling: Marketing spend did not exceed the ₹2.0 Cr quarterly allocation limit.",
        "Operating margin constraint: Operating margin remained above the 25.0% enterprise policy floor.",
        "Inventory capacity: Fulfilment warehouse capacity was fully respected without overtime penalties.",
      ],
      evidenceSources: [
        "Marketing telemetry (Google & Meta campaign conversion logs)",
        "Sales telemetry (CRM opportunity stage velocity & win rates)",
        "Financial telemetry (ERP general ledger quarterly spend reconciliation)",
      ],
    },
    uncertainty: {
      confidenceScore: 78,
      explanation:
        "Confidence reflects the strength of the available historical evidence supporting the counterfactual scenario in this mock dataset.",
      ranges: [
        { metric: "Revenue", range: "₹49.8 Cr – ₹52.1 Cr" },
        { metric: "Gross Profit", range: "₹21.0 Cr – ₹23.0 Cr" },
      ],
    },
    evidenceProgression: [
      {
        id: "ep_1",
        stepNumber: 1,
        title: "Decision made",
        description: "Executive sign-off on 18% paid allocation increase under ₹2.0 Cr constraint.",
        timestamp: "15 Jun 2026, 09:30",
      },
      {
        id: "ep_2",
        stepNumber: 2,
        title: "Marketing allocation changed",
        description: "Capital injected into general Tier-2 ad inventory without segment gating.",
        timestamp: "18 Jun 2026, 11:00",
      },
      {
        id: "ep_3",
        stepNumber: 3,
        title: "Conversion diverged",
        description: "Paid conversion dipped −3.2% while counterfactual model maintained +1.2%.",
        timestamp: "25 Jun 2026, 17:00",
        metricLabel: "Conversion Delta",
        metricValue: "−4.4 pp gap",
      },
      {
        id: "ep_4",
        stepNumber: 4,
        title: "CAC changed",
        description: "Marginal acquisition cost escalated to ₹14,200 per converted enterprise account.",
        timestamp: "02 Jul 2026, 14:15",
        metricLabel: "CAC Divergence",
        metricValue: "+11.2% over model",
      },
      {
        id: "ep_5",
        stepNumber: 5,
        title: "Revenue outcome",
        description: "Actual revenue closed at ₹48.2 Cr compared to ₹51.0 Cr in counterfactual.",
        timestamp: "15 Jul 2026, 18:30",
        metricLabel: "Revenue Opportunity Gap",
        metricValue: "₹2.8 Cr",
      },
      {
        id: "ep_6",
        stepNumber: 6,
        title: "Profit outcome",
        description: "Realized gross profit of ₹19.6 Cr vs ₹22.1 Cr achievable under optimal hedge.",
        timestamp: "18 Jul 2026, 20:00",
        metricLabel: "Net Foregone Margin",
        metricValue: "₹2.5 Cr",
      },
    ],
  },
  hist_dec_02: {
    decision: MOCK_HISTORICAL_DECISIONS[1],
    selectedBranchId: "branch_rebalance_dynamic",
    decisionPoint: {
      date: "02 May 2026",
      title: "Inventory Rebalancing Decision Point",
      originalAction: "Increase Tier-2 inventory allocation",
      description:
        "Operations increased buffer stock in Tier-2 hubs ahead of carrier renegotiations, causing capital lock-up across slow-moving SKUs.",
    },
    actualTimeline: [
      {
        id: "sc_act_w1",
        periodLabel: "Week 1",
        date: "09 May 2026",
        eventTitle: "Buffer stock dispatched to Western hubs",
        explanation: "1,200 units staged in high-cost warehouse zones with zero dynamic reallocation.",
        metricChanges: [
          { label: "Holding Cost", value: "+4.8%", direction: "negative" },
          { label: "Fulfillment SLA", value: "98.2%", direction: "neutral" },
        ],
        statusVariant: "warning",
      },
      {
        id: "sc_act_w2",
        periodLabel: "Week 2",
        date: "16 May 2026",
        eventTitle: "Carrier congestion localized",
        explanation: "Western hubs experienced inventory bottleneck while Eastern hubs faced micro-stockouts.",
        metricChanges: [
          { label: "Carrying Expense", value: "+₹38 L", direction: "negative" },
          { label: "Stockouts", value: "14 incidents", direction: "negative" },
        ],
        statusVariant: "critical",
      },
      {
        id: "sc_act_w4",
        periodLabel: "Week 4",
        date: "30 May 2026",
        eventTitle: "End of month inventory audit",
        explanation: "₹84 L locked in surplus inventory; fulfillment margins depressed by 80 bps.",
        metricChanges: [
          { label: "Working Capital", value: "Trapped ₹84 L", direction: "negative" },
          { label: "Gross Margin", value: "−0.8 pp", direction: "negative" },
        ],
        statusVariant: "neutral",
      },
    ],
    counterfactualTimeline: [
      {
        id: "sc_cf_w1",
        periodLabel: "Week 1",
        date: "09 May 2026",
        eventTitle: "Dynamic multi-hub buffer split",
        explanation: "Dispatched stock evenly across 3 regional nodes with automated cross-dock triggers.",
        metricChanges: [
          { label: "Holding Cost", value: "−1.5%", direction: "positive" },
          { label: "Fulfillment SLA", value: "99.4%", direction: "positive" },
        ],
        statusVariant: "positive",
      },
      {
        id: "sc_cf_w2",
        periodLabel: "Week 2",
        date: "16 May 2026",
        eventTitle: "Cross-docking absorbed regional surge",
        explanation: "No bottleneck; inventory balanced dynamically across eastern & western zones.",
        metricChanges: [
          { label: "Carrying Expense", value: "Zero overage", direction: "positive" },
          { label: "Stockouts", value: "0 incidents", direction: "positive" },
        ],
        statusVariant: "positive",
      },
      {
        id: "sc_cf_w4",
        periodLabel: "Week 4",
        date: "30 May 2026",
        eventTitle: "Working capital preserved",
        explanation: "Achieved 99.6% on-time delivery while releasing ₹84 L in cash liquidity.",
        metricChanges: [
          { label: "Working Capital", value: "+₹84 L freed", direction: "positive" },
          { label: "Gross Margin", value: "+1.2 pp", direction: "positive" },
        ],
        statusVariant: "positive",
      },
    ],
    metrics: [
      {
        key: "working_capital",
        label: "Working Capital Freed",
        actualValue: "₹0",
        counterfactualValue: "₹84 L",
        delta: "+₹84 L",
        deltaType: "positive",
        actualNum: 0,
        counterfactualNum: 84,
        unit: "₹ L",
        explanation: "Cash released by avoiding unnecessary Western warehouse safety buffer overages.",
      },
      {
        key: "holding_costs",
        label: "Holding Costs",
        actualValue: "₹1.42 Cr",
        counterfactualValue: "₹0.98 Cr",
        delta: "−₹44 L",
        deltaType: "positive",
        actualNum: 1.42,
        counterfactualNum: 0.98,
        unit: "₹ Cr",
        explanation: "Lower warehousing lease premiums and deadweight inventory depreciation.",
      },
      {
        key: "on_time_delivery",
        label: "On-Time Delivery",
        actualValue: "96.4%",
        counterfactualValue: "99.2%",
        delta: "+2.8 pp",
        deltaType: "positive",
        actualNum: 96.4,
        counterfactualNum: 99.2,
        unit: "%",
        explanation: "Cross-docking eliminated cross-country transit delays.",
      },
      {
        key: "stockout_incidents",
        label: "Stockout Incidents",
        actualValue: "18",
        counterfactualValue: "2",
        delta: "−16",
        deltaType: "positive",
        actualNum: 18,
        counterfactualNum: 2,
        unit: "Incidents",
        explanation: "Near-total elimination of regional stock depletion events.",
      },
      {
        key: "operating_margin",
        label: "Operating Margin",
        actualValue: "31.2%",
        counterfactualValue: "32.4%",
        delta: "+1.2 pp",
        deltaType: "positive",
        actualNum: 31.2,
        counterfactualNum: 32.4,
        unit: "%",
        explanation: "Reduced expediting freight charges protected unit profitability.",
      },
    ],
    insight: {
      headline: "Counterfactual Supply Chain Insight",
      summary:
        "Dynamic multi-hub buffer allocation would have released ₹84 L in trapped working capital while boosting fulfillment reliability to 99.2%.",
      revenueDiff: "+₹84 L",
      profitDiff: "+₹44 L",
      marginDiff: "+1.2 pp",
      whatChangedExplanation:
        "Rather than dumping bulk inventory into a single western hub, the counterfactual deployed split staging with demand-sensing replenishment rules.",
    },
    evidence: {
      supportingSignals: [
        "Regional demand variance was 42% lower when shared across 3 interconnected fulfillment zones.",
        "Transit hub carrying costs were 18% lower on average than fixed central warehouse fees.",
        "Zero high-priority stockout alarms logged under simulated cross-docking.",
      ],
      constraintsPreserved: [
        "Holding cost variance maintained below the 4.0% policy cap.",
        "Supplier SLA lead times satisfied with 2.5 days safety headroom.",
        "Logistics partner contract volume minimums achieved.",
      ],
      evidenceSources: [
        "WMS inventory tracking (RFID scan & rack occupancy telemetry)",
        "Freight carrier manifest & transit delay telemetry",
        "ERP inventory valuation ledger",
      ],
    },
    uncertainty: {
      confidenceScore: 82,
      explanation:
        "Historical warehouse telemetry provides high fidelity regarding storage costs and fulfillment route times.",
      ranges: [
        { metric: "Working Capital Freed", range: "₹76 L – ₹92 L" },
        { metric: "Holding Cost Savings", range: "₹38 L – ₹49 L" },
      ],
    },
    evidenceProgression: [
      {
        id: "sc_ep_1",
        stepNumber: 1,
        title: "Decision made",
        description: "Approved single-hub inventory buffer buildup ahead of carrier contract talks.",
        timestamp: "02 May 2026, 10:00",
      },
      {
        id: "sc_ep_2",
        stepNumber: 2,
        title: "Western warehouse staging",
        description: "1,200 units shipped directly to western hub, exceeding 60-day target buffer.",
        timestamp: "05 May 2026, 14:00",
      },
      {
        id: "sc_ep_3",
        stepNumber: 3,
        title: "Holding costs spiked",
        description: "Warehouse fees increased 4.8% while alternative dynamic split would have saved cost.",
        timestamp: "12 May 2026, 16:30",
        metricLabel: "Holding Cost Surge",
        metricValue: "+₹38 L",
      },
      {
        id: "sc_ep_4",
        stepNumber: 4,
        title: "Stockouts emerged in Eastern zones",
        description: "14 localized stockouts occurred due to lack of multi-hub rebalancing.",
        timestamp: "20 May 2026, 09:15",
        metricLabel: "Missed Orders",
        metricValue: "18 stockouts",
      },
      {
        id: "sc_ep_5",
        stepNumber: 5,
        title: "Quarterly liquidity impact",
        description: "₹84 L in cash remained trapped in slow-turning safety stock.",
        timestamp: "30 May 2026, 18:00",
        metricLabel: "Trapped Liquidity",
        metricValue: "₹84 L",
      },
    ],
  },
  hist_dec_03: {
    decision: MOCK_HISTORICAL_DECISIONS[2],
    selectedBranchId: "branch_price_bundle",
    decisionPoint: {
      date: "18 April 2026",
      title: "Pricing Adjustment Decision Point",
      originalAction: "Reduce selected product pricing by 5%",
      description:
        "Commercial leadership approved a 5% discount across Mid-Market accounts to fend off competitive churn, compressing gross margins.",
    },
    actualTimeline: [
      {
        id: "pr_act_w1",
        periodLabel: "Week 1",
        date: "25 April 2026",
        eventTitle: "Discount applied to renewal pipeline",
        explanation: "12 accounts renewed quickly, but average selling price contracted across the board.",
        metricChanges: [
          { label: "ASP", value: "−5.0%", direction: "negative" },
          { label: "Renewal Rate", value: "+2.1%", direction: "positive" },
        ],
        statusVariant: "warning",
      },
      {
        id: "pr_act_w2",
        periodLabel: "Week 2",
        date: "02 May 2026",
        eventTitle: "Margin compression evident",
        explanation: "Competitors matched discounts within 10 days, neutralizing the initial conversion lift.",
        metricChanges: [
          { label: "Gross Margin", value: "−1.8 pp", direction: "negative" },
          { label: "Competitive Win Rate", value: "Flat (48%)", direction: "neutral" },
        ],
        statusVariant: "critical",
      },
      {
        id: "pr_act_w4",
        periodLabel: "Week 4",
        date: "16 May 2026",
        eventTitle: "Revenue impact finalized",
        explanation: "Top-line expanded marginally but net operating profit dropped ₹1.1 Cr.",
        metricChanges: [
          { label: "Net Operating Profit", value: "−₹1.1 Cr", direction: "negative" },
          { label: "Customer Lifetime Value", value: "−6.4%", direction: "negative" },
        ],
        statusVariant: "neutral",
      },
    ],
    counterfactualTimeline: [
      {
        id: "pr_cf_w1",
        periodLabel: "Week 1",
        date: "25 April 2026",
        eventTitle: "Feature bundle rolled out",
        explanation: "Preserved headline price and bundled telemetry add-on with 88% gross margin.",
        metricChanges: [
          { label: "ASP", value: "Stable (+0.4%)", direction: "positive" },
          { label: "Renewal Rate", value: "+3.8%", direction: "positive" },
        ],
        statusVariant: "positive",
      },
      {
        id: "pr_cf_w2",
        periodLabel: "Week 2",
        date: "02 May 2026",
        eventTitle: "Value differentiation captured",
        explanation: "Competitors were unable to match telemetry features, preserving deal win rate.",
        metricChanges: [
          { label: "Gross Margin", value: "+0.6 pp", direction: "positive" },
          { label: "Competitive Win Rate", value: "59% (+11 pp)", direction: "positive" },
        ],
        statusVariant: "positive",
      },
      {
        id: "pr_cf_w4",
        periodLabel: "Week 4",
        date: "16 May 2026",
        eventTitle: "Sustainable expansion achieved",
        explanation: "Retained full pricing power and expanded ARR by ₹1.6 Cr without discounting precedent.",
        metricChanges: [
          { label: "Net Operating Profit", value: "+₹1.6 Cr", direction: "positive" },
          { label: "Customer Lifetime Value", value: "+8.2%", direction: "positive" },
        ],
        statusVariant: "positive",
      },
    ],
    metrics: [
      {
        key: "net_profit",
        label: "Net Operating Profit",
        actualValue: "₹14.2 Cr",
        counterfactualValue: "₹15.8 Cr",
        delta: "+₹1.6 Cr",
        deltaType: "positive",
        actualNum: 14.2,
        counterfactualNum: 15.8,
        unit: "₹ Cr",
        explanation: "Value-add bundling prevented margin dilution while keeping enterprise churn under 0.2%.",
      },
      {
        key: "asp",
        label: "Average Contract Value (ACV)",
        actualValue: "₹18.4 L",
        counterfactualValue: "₹20.2 L",
        delta: "+₹1.8 L",
        deltaType: "positive",
        actualNum: 18.4,
        counterfactualNum: 20.2,
        unit: "₹ L",
        explanation: "Maintained baseline pricing integrity and expanded contract scope.",
      },
      {
        key: "gross_margin",
        label: "Gross Margin",
        actualValue: "68.2%",
        counterfactualValue: "70.6%",
        delta: "+2.4 pp",
        deltaType: "positive",
        actualNum: 68.2,
        counterfactualNum: 70.6,
        unit: "%",
        explanation: "High-margin software telemetry bundle diluted COGS ratio.",
      },
      {
        key: "win_rate",
        label: "Competitive Win Rate",
        actualValue: "48%",
        counterfactualValue: "59%",
        delta: "+11 pp",
        deltaType: "positive",
        actualNum: 48,
        counterfactualNum: 59,
        unit: "%",
        explanation: "Differentiated service package outperformed competitor generic price cuts.",
      },
    ],
    insight: {
      headline: "Counterfactual Pricing Insight",
      summary:
        "Feature bundling instead of pure discounting would have retained pricing power, generating ₹1.6 Cr more profit and lifting margins by 2.4 pp.",
      revenueDiff: "+₹1.6 Cr",
      profitDiff: "+₹1.6 Cr",
      marginDiff: "+2.4 pp",
      whatChangedExplanation:
        "Rather than triggering a commodity price race with competitors, the counterfactual fortified deal value with proprietary telemetry tools.",
    },
    evidence: {
      supportingSignals: [
        "82% of renewing accounts surveyed preferred enhanced SLA tools over minor upfront price discounts.",
        "Price reduction was matched by primary competitor within 10 days, negating market share advantage.",
        "Software telemetry bundle carried a 94% marginal contribution margin.",
      ],
      constraintsPreserved: [
        "Contribution margin maintained well above the 28.0% minimum threshold at 70.6%.",
        "Quarterly net retention rate target of 115% achieved.",
        "Sales team commission compensation structures aligned without exception waivers.",
      ],
      evidenceSources: [
        "Salesforce CPQ quote discount logs & win/loss analysis",
        "Customer success telemetry & quarterly renewal surveys",
        "Finance revenue recognition ledger",
      ],
    },
    uncertainty: {
      confidenceScore: 74,
      explanation:
        "Confidence is influenced by competitor price matching response times and renewal cohort size.",
      ranges: [
        { metric: "Net Profit Delta", range: "₹1.2 Cr – ₹1.9 Cr" },
        { metric: "Gross Margin Delta", range: "+1.8 pp – +2.9 pp" },
      ],
    },
    evidenceProgression: [
      {
        id: "pr_ep_1",
        stepNumber: 1,
        title: "Decision made",
        description: "Enacted 5% discount across Mid-Market renewals to defend against competitor moves.",
        timestamp: "18 Apr 2026, 11:30",
      },
      {
        id: "pr_ep_2",
        stepNumber: 2,
        title: "Discount applied to quotes",
        description: "CPQ pricing matrices adjusted across Tier-2 SaaS accounts.",
        timestamp: "20 Apr 2026, 09:00",
      },
      {
        id: "pr_ep_3",
        stepNumber: 3,
        title: "Competitor matched price",
        description: "Competitor dropped prices within 10 days, neutralizing initial conversion uplift.",
        timestamp: "30 Apr 2026, 15:45",
        metricLabel: "Price Advantage Duration",
        metricValue: "10 days",
      },
      {
        id: "pr_ep_4",
        stepNumber: 4,
        title: "Margin compression",
        description: "Realized gross margin dipped 1.8 pp below baseline.",
        timestamp: "08 May 2026, 14:00",
        metricLabel: "Margin Loss",
        metricValue: "−1.8 pp",
      },
      {
        id: "pr_ep_5",
        stepNumber: 5,
        title: "Profit erosion finalized",
        description: "Finished quarter with ₹1.1 Cr in unforced profit erosion vs alternative bundling.",
        timestamp: "16 May 2026, 18:00",
        metricLabel: "Foregone Profit",
        metricValue: "₹1.6 Cr opportunity",
      },
    ],
  },
};

export const DEFAULT_REPLAY_DECISION_ID = "hist_dec_01";
