import {
  DecisionLeverConfig,
  DecisionLeverValues,
  ScenarioPreset,
  ScenarioWorkspaceData,
  SimulationHistoryEntry,
  SavedScenario,
} from "@/types/scenario-workspace";

export const DECISION_LEVER_CONFIGS: DecisionLeverConfig[] = [
  {
    key: "marketingBudget",
    label: "Marketing Budget",
    min: 1.0,
    max: 2.0,
    step: 0.05,
    unit: "₹ Cr",
    baseline: 1.4,
    description: "Quarterly allocation across digital and account-based enterprise marketing channels.",
  },
  {
    key: "workingInventory",
    label: "Working Inventory",
    min: 500,
    max: 1500,
    step: 25,
    unit: "units",
    baseline: 900,
    description: "Regional buffer inventory maintained across primary fulfillment centers.",
  },
  {
    key: "unitPrice",
    label: "Unit Price",
    min: 90,
    max: 120,
    step: 1,
    unit: "₹",
    baseline: 105,
    description: "Effective average contract invoice price point across Mid-Market accounts.",
  },
];

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: "preset_baseline",
    name: "Baseline",
    tagline: "Current operating plan",
    description: "Maintains existing approved quarterly targets and budget allocations.",
    levers: {
      marketingBudget: 1.4,
      workingInventory: 900,
      unitPrice: 105,
    },
    badge: "Active Baseline",
  },
  {
    id: "preset_growth",
    name: "Growth Push",
    tagline: "Aggressive market capture",
    description: "Increase marketing investment and inventory availability to maximize new deal volume.",
    levers: {
      marketingBudget: 1.85,
      workingInventory: 1300,
      unitPrice: 102,
    },
    badge: "Topline Focus",
  },
  {
    id: "preset_efficiency",
    name: "Efficiency Focus",
    tagline: "Capital conservation & ROAS",
    description: "Reduce inefficient marketing spend and improve channel allocation for maximum gross return.",
    levers: {
      marketingBudget: 1.25,
      workingInventory: 850,
      unitPrice: 108,
    },
    badge: "Recommended",
  },
  {
    id: "preset_margin",
    name: "Margin Protection",
    tagline: "Pricing power & cash flow",
    description: "Increase price while controlling inventory holding costs and acquisition spending.",
    levers: {
      marketingBudget: 1.2,
      workingInventory: 750,
      unitPrice: 115,
    },
    badge: "High Margin",
  },
];

export const MOCK_SCENARIO_WORKSPACES: Record<string, ScenarioWorkspaceData> = {
  preset_baseline: {
    presetId: "preset_baseline",
    scenarioName: "Baseline Operating Plan",
    lastSimulatedAt: "Today, 10:15",
    levers: {
      marketingBudget: 1.4,
      workingInventory: 900,
      unitPrice: 105,
    },
    metrics: [
      {
        key: "revenue",
        label: "Revenue",
        currentValue: "₹48.2 Cr",
        simulatedValue: "₹48.2 Cr",
        change: "0.0%",
        changeType: "neutral",
        currentNum: 48.2,
        simulatedNum: 48.2,
        unit: "₹ Cr",
      },
      {
        key: "gross_profit",
        label: "Gross Profit",
        currentValue: "₹19.6 Cr",
        simulatedValue: "₹19.6 Cr",
        change: "0.0%",
        changeType: "neutral",
        currentNum: 19.6,
        simulatedNum: 19.6,
        unit: "₹ Cr",
      },
      {
        key: "operating_margin",
        label: "Operating Margin",
        currentValue: "32.4%",
        simulatedValue: "32.4%",
        change: "0.0 pp",
        changeType: "neutral",
        currentNum: 32.4,
        simulatedNum: 32.4,
        unit: "%",
      },
      {
        key: "orders",
        label: "Orders",
        currentValue: "14,820",
        simulatedValue: "14,820",
        change: "0.0%",
        changeType: "neutral",
        currentNum: 14820,
        simulatedNum: 14820,
        unit: "Orders",
      },
      {
        key: "inventory",
        label: "Inventory Value",
        currentValue: "₹6.4 Cr",
        simulatedValue: "₹6.4 Cr",
        change: "0.0%",
        changeType: "neutral",
        currentNum: 6.4,
        simulatedNum: 6.4,
        unit: "₹ Cr",
      },
    ],
    sensitivity: [
      {
        leverKey: "marketingBudget",
        leverLabel: "Marketing Budget",
        sensitivityLevel: "High",
        impactScore: 10,
        barFillPercent: 100,
        explanation: "10% shift in marketing capital correlates to a 4.2% swing in quarterly pipeline volume.",
      },
      {
        leverKey: "unitPrice",
        leverLabel: "Unit Price",
        sensitivityLevel: "Medium",
        impactScore: 7,
        barFillPercent: 70,
        explanation: "Price adjustments produce immediate margin impact but carry moderate elasticity risk.",
      },
      {
        leverKey: "workingInventory",
        leverLabel: "Working Inventory",
        sensitivityLevel: "Low",
        impactScore: 4,
        barFillPercent: 40,
        explanation: "Buffer stock fluctuations impact capital liquidity with negligible revenue velocity friction.",
      },
    ],
    tradeoffs: {
      categories: [
        {
          title: "Growth",
          metric1: { label: "Revenue", value: "Flat (0%)", positive: false },
          metric2: { label: "Orders", value: "Flat (0%)", positive: false },
        },
        {
          title: "Profitability",
          metric1: { label: "Gross Profit", value: "₹19.6 Cr", positive: false },
          metric2: { label: "Margin", value: "32.4%", positive: false },
        },
        {
          title: "Capital Efficiency",
          metric1: { label: "Inventory", value: "₹6.4 Cr", positive: false },
          metric2: { label: "Budget", value: "₹1.40 Cr", positive: false },
        },
      ],
      summary: "Baseline operating plan produces steady, unaccelerated performance without testing upside elasticity.",
    },
    constraints: [
      {
        id: "c_budget",
        name: "Quarterly Marketing Budget",
        rule: "Budget ≤ ₹2.0 Cr",
        thresholdValue: "₹2.0 Cr",
        projectedValue: "₹1.40 Cr",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_margin",
        name: "Minimum Operating Margin",
        rule: "Margin ≥ 25.0%",
        thresholdValue: "25.0%",
        projectedValue: "32.4%",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_inventory",
        name: "Warehouse Capacity",
        rule: "Inventory ≤ 1,500 units",
        thresholdValue: "1,500 units",
        projectedValue: "900 units",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
    ],
    uncertainty: {
      confidenceScore: 78,
      explanation: "Confidence reflects the quality and completeness of the inputs available to the simulation in this mock dataset.",
      ranges: [
        { metric: "Revenue Range", range: "₹47.5 Cr – ₹49.1 Cr" },
        { metric: "Gross Profit Range", range: "₹19.1 Cr – ₹20.2 Cr" },
      ],
    },
    history: [],
  },

  // ─── Growth Push Workspace (Primary prompt example) ───
  preset_growth: {
    presetId: "preset_growth",
    scenarioName: "Growth Push",
    lastSimulatedAt: "Today, 14:32",
    levers: {
      marketingBudget: 1.85,
      workingInventory: 1300,
      unitPrice: 102,
    },
    metrics: [
      {
        key: "revenue",
        label: "Revenue",
        currentValue: "₹48.2 Cr",
        simulatedValue: "₹51.4 Cr",
        change: "+6.6%",
        changeType: "positive",
        currentNum: 48.2,
        simulatedNum: 51.4,
        unit: "₹ Cr",
      },
      {
        key: "gross_profit",
        label: "Gross Profit",
        currentValue: "₹19.6 Cr",
        simulatedValue: "₹21.7 Cr",
        change: "+10.7%",
        changeType: "positive",
        currentNum: 19.6,
        simulatedNum: 21.7,
        unit: "₹ Cr",
      },
      {
        key: "operating_margin",
        label: "Operating Margin",
        currentValue: "32.4%",
        simulatedValue: "33.8%",
        change: "+1.4 pp",
        changeType: "positive",
        currentNum: 32.4,
        simulatedNum: 33.8,
        unit: "%",
      },
      {
        key: "orders",
        label: "Orders",
        currentValue: "14,820",
        simulatedValue: "15,940",
        change: "+7.6%",
        changeType: "positive",
        currentNum: 14820,
        simulatedNum: 15940,
        unit: "Orders",
      },
      {
        key: "inventory",
        label: "Inventory Value",
        currentValue: "₹6.4 Cr",
        simulatedValue: "₹6.1 Cr",
        change: "−4.7%",
        changeType: "positive",
        currentNum: 6.4,
        simulatedNum: 6.1,
        unit: "₹ Cr",
      },
    ],
    sensitivity: [
      {
        leverKey: "marketingBudget",
        leverLabel: "Marketing Budget",
        sensitivityLevel: "High",
        impactScore: 10,
        barFillPercent: 100,
        explanation: "Marketing expansion unlocks +₹2.8 Cr in gross revenue velocity via Tier-2 channels.",
      },
      {
        leverKey: "unitPrice",
        leverLabel: "Unit Price",
        sensitivityLevel: "Medium",
        impactScore: 7,
        barFillPercent: 70,
        explanation: "Discounting to ₹102 increases unit sales velocity without breaking margin guidelines.",
      },
      {
        leverKey: "workingInventory",
        leverLabel: "Working Inventory",
        sensitivityLevel: "Low",
        impactScore: 4,
        barFillPercent: 40,
        explanation: "1,300 units provides 99.8% order fulfillment rate with minimal excess carry cost.",
      },
    ],
    tradeoffs: {
      categories: [
        {
          title: "Growth",
          metric1: { label: "Revenue", value: "+6.6%", positive: true },
          metric2: { label: "Orders", value: "+7.6%", positive: true },
        },
        {
          title: "Profitability",
          metric1: { label: "Gross Profit", value: "+10.7%", positive: true },
          metric2: { label: "Margin", value: "+1.4 pp", positive: true },
        },
        {
          title: "Capital Efficiency",
          metric1: { label: "Inventory", value: "−4.7%", positive: true },
          metric2: { label: "Budget Spent", value: "₹1.85 Cr", positive: false },
        },
      ],
      summary:
        "The simulated configuration improves growth and profit while reducing working inventory, but requires additional marketing investment.",
    },
    constraints: [
      {
        id: "c_budget",
        name: "Budget Ceiling",
        rule: "Budget ≤ ₹2.0 Cr",
        thresholdValue: "₹2.0 Cr",
        projectedValue: "₹1.85 Cr",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_margin",
        name: "Margin Floor",
        rule: "Margin ≥ 25.0%",
        thresholdValue: "25.0%",
        projectedValue: "33.8%",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_inventory",
        name: "Inventory Cap",
        rule: "Inventory ≤ 1,500 units",
        thresholdValue: "1,500 units",
        projectedValue: "1,300 units",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
    ],
    uncertainty: {
      confidenceScore: 78,
      explanation:
        "Confidence reflects the quality and completeness of the inputs available to the simulation in this mock dataset.",
      ranges: [
        { metric: "Revenue Range", range: "₹49.8 Cr – ₹52.4 Cr" },
        { metric: "Profit Range", range: "₹20.9 Cr – ₹22.6 Cr" },
      ],
    },
    history: [],
  },

  // ─── Efficiency Focus Workspace ───
  preset_efficiency: {
    presetId: "preset_efficiency",
    scenarioName: "Efficiency Focus",
    lastSimulatedAt: "Today, 11:20",
    levers: {
      marketingBudget: 1.25,
      workingInventory: 850,
      unitPrice: 108,
    },
    metrics: [
      {
        key: "revenue",
        label: "Revenue",
        currentValue: "₹48.2 Cr",
        simulatedValue: "₹49.6 Cr",
        change: "+2.9%",
        changeType: "positive",
        currentNum: 48.2,
        simulatedNum: 49.6,
        unit: "₹ Cr",
      },
      {
        key: "gross_profit",
        label: "Gross Profit",
        currentValue: "₹19.6 Cr",
        simulatedValue: "₹21.7 Cr",
        change: "+10.7%",
        changeType: "positive",
        currentNum: 19.6,
        simulatedNum: 21.7,
        unit: "₹ Cr",
      },
      {
        key: "operating_margin",
        label: "Operating Margin",
        currentValue: "32.4%",
        simulatedValue: "34.6%",
        change: "+2.2 pp",
        changeType: "positive",
        currentNum: 32.4,
        simulatedNum: 34.6,
        unit: "%",
      },
      {
        key: "orders",
        label: "Orders",
        currentValue: "14,820",
        simulatedValue: "15,100",
        change: "+1.9%",
        changeType: "positive",
        currentNum: 14820,
        simulatedNum: 15100,
        unit: "Orders",
      },
      {
        key: "inventory",
        label: "Inventory Value",
        currentValue: "₹6.4 Cr",
        simulatedValue: "₹5.7 Cr",
        change: "−10.9%",
        changeType: "positive",
        currentNum: 6.4,
        simulatedNum: 5.7,
        unit: "₹ Cr",
      },
    ],
    sensitivity: [
      {
        leverKey: "marketingBudget",
        leverLabel: "Marketing Budget",
        sensitivityLevel: "High",
        impactScore: 10,
        barFillPercent: 100,
        explanation: "Cutting low-intent search terms releases ₹15 L in capital without volume loss.",
      },
      {
        leverKey: "unitPrice",
        leverLabel: "Unit Price",
        sensitivityLevel: "Medium",
        impactScore: 7,
        barFillPercent: 70,
        explanation: "₹108 price point preserves pricing power with negligible renewal pushback.",
      },
      {
        leverKey: "workingInventory",
        leverLabel: "Working Inventory",
        sensitivityLevel: "Low",
        impactScore: 4,
        barFillPercent: 40,
        explanation: "850 units keeps inventory turns at a lean 6.2x annual rate.",
      },
    ],
    tradeoffs: {
      categories: [
        {
          title: "Growth",
          metric1: { label: "Revenue", value: "+2.9%", positive: true },
          metric2: { label: "Orders", value: "+1.9%", positive: true },
        },
        {
          title: "Profitability",
          metric1: { label: "Gross Profit", value: "+10.7%", positive: true },
          metric2: { label: "Margin", value: "+2.2 pp", positive: true },
        },
        {
          title: "Capital Efficiency",
          metric1: { label: "Inventory", value: "−10.9%", positive: true },
          metric2: { label: "Cash Freed", value: "+₹15 L", positive: true },
        },
      ],
      summary:
        "High ROAS strategy that accelerates margin expansion to 34.6% while freeing ₹70 L in tied inventory capital.",
    },
    constraints: [
      {
        id: "c_budget",
        name: "Budget Ceiling",
        rule: "Budget ≤ ₹2.0 Cr",
        thresholdValue: "₹2.0 Cr",
        projectedValue: "₹1.25 Cr",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_margin",
        name: "Margin Floor",
        rule: "Margin ≥ 25.0%",
        thresholdValue: "25.0%",
        projectedValue: "34.6%",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_inventory",
        name: "Inventory Cap",
        rule: "Inventory ≤ 1,500 units",
        thresholdValue: "1,500 units",
        projectedValue: "850 units",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
    ],
    uncertainty: {
      confidenceScore: 84,
      explanation:
        "High empirical confidence due to stable historical unit economics in low-spend regimes.",
      ranges: [
        { metric: "Revenue Range", range: "₹48.9 Cr – ₹50.2 Cr" },
        { metric: "Profit Range", range: "₹21.2 Cr – ₹22.1 Cr" },
      ],
    },
    history: [],
  },

  // ─── Margin Protection Workspace ───
  preset_margin: {
    presetId: "preset_margin",
    scenarioName: "Margin Protection",
    lastSimulatedAt: "Today, 09:40",
    levers: {
      marketingBudget: 1.2,
      workingInventory: 750,
      unitPrice: 115,
    },
    metrics: [
      {
        key: "revenue",
        label: "Revenue",
        currentValue: "₹48.2 Cr",
        simulatedValue: "₹49.1 Cr",
        change: "+1.9%",
        changeType: "positive",
        currentNum: 48.2,
        simulatedNum: 49.1,
        unit: "₹ Cr",
      },
      {
        key: "gross_profit",
        label: "Gross Profit",
        currentValue: "₹19.6 Cr",
        simulatedValue: "₹22.4 Cr",
        change: "+14.3%",
        changeType: "positive",
        currentNum: 19.6,
        simulatedNum: 22.4,
        unit: "₹ Cr",
      },
      {
        key: "operating_margin",
        label: "Operating Margin",
        currentValue: "32.4%",
        simulatedValue: "35.8%",
        change: "+3.4 pp",
        changeType: "positive",
        currentNum: 32.4,
        simulatedNum: 35.8,
        unit: "%",
      },
      {
        key: "orders",
        label: "Orders",
        currentValue: "14,820",
        simulatedValue: "14,350",
        change: "−3.2%",
        changeType: "negative",
        currentNum: 14820,
        simulatedNum: 14350,
        unit: "Orders",
      },
      {
        key: "inventory",
        label: "Inventory Value",
        currentValue: "₹6.4 Cr",
        simulatedValue: "₹5.2 Cr",
        change: "−18.8%",
        changeType: "positive",
        currentNum: 6.4,
        simulatedNum: 5.2,
        unit: "₹ Cr",
      },
    ],
    sensitivity: [
      {
        leverKey: "unitPrice",
        leverLabel: "Unit Price",
        sensitivityLevel: "High",
        impactScore: 10,
        barFillPercent: 100,
        explanation: "Price increase to ₹115 generates +₹2.8 Cr in gross margin expansion.",
      },
      {
        leverKey: "marketingBudget",
        leverLabel: "Marketing Budget",
        sensitivityLevel: "Medium",
        impactScore: 6,
        barFillPercent: 60,
        explanation: "Budget moderated to ₹1.20 Cr to filter for price-insensitive enterprise accounts.",
      },
      {
        leverKey: "workingInventory",
        leverLabel: "Working Inventory",
        sensitivityLevel: "Low",
        impactScore: 4,
        barFillPercent: 40,
        explanation: "Lean stock holdings protect cash while supporting slightly lower order volumes.",
      },
    ],
    tradeoffs: {
      categories: [
        {
          title: "Growth",
          metric1: { label: "Revenue", value: "+1.9%", positive: true },
          metric2: { label: "Orders", value: "−3.2%", positive: false },
        },
        {
          title: "Profitability",
          metric1: { label: "Gross Profit", value: "+14.3%", positive: true },
          metric2: { label: "Margin", value: "+3.4 pp", positive: true },
        },
        {
          title: "Capital Efficiency",
          metric1: { label: "Inventory", value: "−18.8%", positive: true },
          metric2: { label: "Working Cap Freed", value: "+₹1.2 Cr", positive: true },
        },
      ],
      summary:
        "Sacrifices 3.2% in order volume to capture a massive 35.8% operating margin and ₹22.4 Cr in gross profit.",
    },
    constraints: [
      {
        id: "c_budget",
        name: "Budget Ceiling",
        rule: "Budget ≤ ₹2.0 Cr",
        thresholdValue: "₹2.0 Cr",
        projectedValue: "₹1.20 Cr",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_margin",
        name: "Margin Floor",
        rule: "Margin ≥ 25.0%",
        thresholdValue: "25.0%",
        projectedValue: "35.8%",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
      {
        id: "c_inventory",
        name: "Inventory Cap",
        rule: "Inventory ≤ 1,500 units",
        thresholdValue: "1,500 units",
        projectedValue: "750 units",
        status: "within_constraint",
        statusLabel: "Within Constraint",
      },
    ],
    uncertainty: {
      confidenceScore: 72,
      explanation:
        "Price elasticity models carry minor uncertainty for newly onboarded Tier-2 customer segments.",
      ranges: [
        { metric: "Revenue Range", range: "₹48.1 Cr – ₹50.0 Cr" },
        { metric: "Profit Range", range: "₹21.6 Cr – ₹23.1 Cr" },
      ],
    },
    history: [],
  },
};

export const MOCK_SIMULATION_HISTORY: SimulationHistoryEntry[] = [
  {
    id: "hist_1",
    timeframe: "Today",
    scenarioName: "Efficiency Focus",
    timestamp: "14:30",
    levers: {
      marketing: "₹1.35 Cr",
      inventory: "850",
      price: "₹108",
    },
    highlightResult: "+10.7% Gross Profit",
  },
  {
    id: "hist_2",
    timeframe: "Yesterday",
    scenarioName: "Growth Push",
    timestamp: "16:45",
    levers: {
      marketing: "₹1.75 Cr",
      inventory: "1,200",
      price: "₹102",
    },
    highlightResult: "+8.1% Revenue",
  },
  {
    id: "hist_3",
    timeframe: "2 days ago",
    scenarioName: "Margin Protection Baseline",
    timestamp: "11:15",
    levers: {
      marketing: "₹1.20 Cr",
      inventory: "800",
      price: "₹112",
    },
    highlightResult: "+2.8 pp Operating Margin",
  },
];

export const INITIAL_SAVED_SCENARIOS: SavedScenario[] = [
  {
    id: "saved_1",
    name: "Q3 Aggressive Inbound Mix",
    createdAt: "28 Sep 2026",
    levers: {
      marketingBudget: 1.65,
      workingInventory: 1100,
      unitPrice: 104,
    },
    projectedRevenue: "₹50.8 Cr",
    projectedProfit: "₹21.1 Cr",
    projectedMargin: "33.2%",
  },
  {
    id: "saved_2",
    name: "Conservative Cash Buffer Plan",
    createdAt: "25 Sep 2026",
    levers: {
      marketingBudget: 1.25,
      workingInventory: 800,
      unitPrice: 110,
    },
    projectedRevenue: "₹49.2 Cr",
    projectedProfit: "₹21.9 Cr",
    projectedMargin: "34.8%",
  },
];

export const DEFAULT_PRESET_ID = "preset_growth";
