"""
DecisionOS — Opportunity MongoDB Document Model

Stores detected decision opportunities generated by the deterministic
detection engine across enterprise business telemetry and Digital Twin metrics.
"""

from datetime import datetime, timezone
from typing import Any, Optional
from pydantic import BaseModel, Field


class OpportunityImpactModel(BaseModel):
    """Financial and operational impact estimation for an opportunity."""
    projected_revenue: float = 0.0
    cost_reduction: float = 0.0
    net_value: float = 0.0
    confidence_score: float = 0.0  # 0 to 100
    time_to_realization_days: int = 14
    net_value_formatted: str = "₹0"
    time_horizon: str = "14 days"
    risk_level: str = "medium"  # low | medium | high

    @property
    def projectedRevenue(self) -> float:
        return self.projected_revenue

    @property
    def costReduction(self) -> float:
        return self.cost_reduction

    @property
    def netValue(self) -> float:
        return self.net_value

    @property
    def confidenceScore(self) -> float:
        return self.confidence_score

    @property
    def timeToRealizationDays(self) -> int:
        return self.time_to_realization_days

    @property
    def netValueFormatted(self) -> str:
        return self.net_value_formatted

    @property
    def timeHorizon(self) -> str:
        return self.time_horizon

    @property
    def riskLevel(self) -> str:
        return self.risk_level

    def to_dict(self) -> dict[str, Any]:
        return {
            "projectedRevenue": self.projected_revenue,
            "projected_revenue": self.projected_revenue,
            "costReduction": self.cost_reduction,
            "cost_reduction": self.cost_reduction,
            "netValue": self.net_value,
            "net_value": self.net_value,
            "confidenceScore": self.confidence_score,
            "confidence_score": self.confidence_score,
            "timeToRealizationDays": self.time_to_realization_days,
            "time_to_realization_days": self.time_to_realization_days,
            "netValueFormatted": self.net_value_formatted,
            "net_value_formatted": self.net_value_formatted,
            "timeHorizon": self.time_horizon,
            "time_horizon": self.time_horizon,
            "riskLevel": self.risk_level,
            "risk_level": self.risk_level,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "OpportunityImpactModel":
        return cls(
            project_revenue=float(data.get("projectedRevenue") or data.get("projected_revenue", 0.0)),
            cost_reduction=float(data.get("costReduction") or data.get("cost_reduction", 0.0)),
            net_value=float(data.get("netValue") or data.get("net_value", 0.0)),
            confidence_score=float(data.get("confidenceScore") or data.get("confidence_score", 0.0)),
            time_to_realization_days=int(data.get("timeToRealizationDays") or data.get("time_to_realization_days", 14)),
            net_value_formatted=str(data.get("netValueFormatted") or data.get("net_value_formatted", "₹0")),
            time_horizon=str(data.get("timeHorizon") or data.get("time_horizon", "14 days")),
            risk_level=str(data.get("riskLevel") or data.get("risk_level", "medium")),
        )


class OpportunitySignalModel(BaseModel):
    """A detected anomaly or trend signal that triggered the opportunity."""
    id: str
    label: str
    metric: str
    value: str
    direction: str = "negative"  # positive | negative | neutral
    group: str = "negative"      # positive | negative | monitoring
    description: Optional[str] = None
    observed_value: Optional[float] = None
    baseline_value: Optional[float] = None
    change_percent: Optional[float] = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "label": self.label,
            "metric": self.metric,
            "value": self.value,
            "direction": self.direction,
            "group": self.group,
            "description": self.description,
            "observedValue": self.observed_value,
            "observed_value": self.observed_value,
            "baselineValue": self.baseline_value,
            "baseline_value": self.baseline_value,
            "changePercent": self.change_percent,
            "change_percent": self.change_percent,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "OpportunitySignalModel":
        return cls(
            id=str(data.get("id", "")),
            label=str(data.get("label", "")),
            metric=str(data.get("metric", "")),
            value=str(data.get("value", "")),
            direction=str(data.get("direction", "negative")),
            group=str(data.get("group", "negative")),
            description=data.get("description"),
            observed_value=data.get("observedValue") or data.get("observed_value"),
            baseline_value=data.get("baselineValue") or data.get("baseline_value"),
            change_percent=data.get("changePercent") or data.get("change_percent"),
        )


class OpportunityDocument(BaseModel):
    """
    Represents an Opportunity document stored in 'opportunities'.

    Fields:
        id (str):                UUID string used as MongoDB _id (opportunityId).
        code (str):              Human-readable code (e.g. OPP-9021).
        organization_id (str):   FK -> organizations._id (Root tenant isolation).
        business_id (str):       FK -> businesses._id.
        title (str):             Actionable title of the decision opportunity.
        summary (str):           Concise analytical synopsis.
        category (str):          pricing_optimization | inventory_rebalance | operational_efficiency | churn_prevention | revenue | supply_chain | cross_sell
        priority (str):          critical | high | medium | low (also mapped to urgency)
        urgency (str):           critical | high | medium | low
        status (str):            detected | in_investigation | decision_ready | executed | dismissed | resolved
        confidence (float):      Overall confidence score (0 to 100).
        impact (OpportunityImpactModel): Projected financial and timeline impacts.
        signals (list):          List of observed anomaly telemetry signals.
        affected_segments (list): Segments impacted (e.g. Tier-2 Paid, West Region).
        tags (list):             Categorical tags.
        detected_at (datetime):  Timestamp of detection.
        updated_at (datetime):   Timestamp of last evaluation.
    """

    id: str = Field(..., description="UUID string - used as MongoDB _id (opportunityId)")
    code: str
    organization_id: str
    business_id: str
    dataset_id: str = Field(default="", description="FK -> datasets._id. Scopes this opportunity to the dataset that generated it.")
    title: str
    summary: str
    category: str
    priority: str = "high"
    urgency: str = "high"
    status: str = "detected"
    confidence: float = 85.0
    impact: OpportunityImpactModel = Field(default_factory=OpportunityImpactModel)
    signals: list[OpportunitySignalModel] = Field(default_factory=list)
    affected_segments: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def opportunityId(self) -> str:
        return self.id

    @property
    def opportunity_id(self) -> str:
        return self.id

    @property
    def organizationId(self) -> str:
        return self.organization_id

    @property
    def businessId(self) -> str:
        return self.business_id

    @property
    def affectedSegments(self) -> list[str]:
        return self.affected_segments

    @property
    def detectedAt(self) -> datetime:
        return self.detected_at

    @property
    def updatedAt(self) -> datetime:
        return self.updated_at

    def to_mongo(self) -> dict[str, Any]:
        """Serializes document for MongoDB persistence with dual-naming for compatibility."""
        return {
            "_id": self.id,
            "opportunityId": self.id,
            "opportunity_id": self.id,
            "code": self.code,
            "organization_id": self.organization_id,
            "organizationId": self.organization_id,
            "business_id": self.business_id,
            "businessId": self.business_id,
            "dataset_id": self.dataset_id,
            "datasetId": self.dataset_id,
            "title": self.title,
            "summary": self.summary,
            "category": self.category,
            "priority": self.priority,
            "urgency": self.urgency,
            "status": self.status,
            "confidence": self.confidence,
            "impact": self.impact.to_dict(),
            "signals": [s.to_dict() for s in self.signals],
            "affected_segments": self.affected_segments,
            "affectedSegments": self.affected_segments,
            "tags": self.tags,
            "detected_at": self.detected_at,
            "detectedAt": self.detected_at,
            "updated_at": self.updated_at,
            "updatedAt": self.updated_at,
        }

    @classmethod
    def from_mongo(cls, doc: dict[str, Any]) -> "OpportunityDocument":
        """Reconstructs model from MongoDB document."""
        impact_raw = doc.get("impact") or {}
        signals_raw = doc.get("signals") or []

        prio = str(doc.get("priority") or doc.get("urgency") or "high")
        urg = str(doc.get("urgency") or doc.get("priority") or "high")

        return cls(
            id=str(doc.get("_id") or doc.get("opportunityId") or doc.get("opportunity_id")),
            code=str(doc.get("code", "OPP-0000")),
            organization_id=str(doc.get("organization_id") or doc.get("organizationId")),
            business_id=str(doc.get("business_id") or doc.get("businessId")),
            dataset_id=str(doc.get("dataset_id") or doc.get("datasetId") or ""),
            title=str(doc.get("title", "")),
            summary=str(doc.get("summary", "")),
            category=str(doc.get("category", "revenue")),
            priority=prio,
            urgency=urg,
            status=str(doc.get("status", "detected")),
            confidence=float(doc.get("confidence") or impact_raw.get("confidenceScore") or impact_raw.get("confidence_score") or 85.0),
            impact=OpportunityImpactModel.from_dict(impact_raw) if isinstance(impact_raw, dict) else OpportunityImpactModel(),
            signals=[OpportunitySignalModel.from_dict(s) for s in signals_raw if isinstance(s, dict)],
            affected_segments=doc.get("affected_segments") or doc.get("affectedSegments") or [],
            tags=doc.get("tags") or [],
            detected_at=doc.get("detected_at") or doc.get("detectedAt") or datetime.now(timezone.utc),
            updated_at=doc.get("updated_at") or doc.get("updatedAt") or datetime.now(timezone.utc),
        )
