"use client";

import * as React from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { RefreshCw, AlertCircle, ArrowLeft } from "lucide-react";
import { AppLayout } from "@/components/layout/app-layout";
import { PageContainer } from "@/components/layout/page-container";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

// Investigation components
import {
  InvestigationHeader,
  OpportunityContextCard,
  SignalSummary,
  HypothesisList,
  DecisionTreeVisualization,
  EvidenceExplorer,
  InvestigationSummary,
  InvestigationTimeline,
  NextDecisionActions,
} from "@/components/investigation";
import { WorkflowStepBanner } from "@/components/shared/workflow-step-banner";

// Repositories & Types
import { getInvestigationRepository, getOpportunityRepository } from "@/lib/repositories";
import { Opportunity } from "@/types/opportunity";
import {
  InvestigationWorkspace,
  InvestigationWorkspaceHypothesis,
} from "@/types/investigation-workspace";

// ─── Loading skeleton ─────────────────────────────────────────────────────────

function InvestigationSkeleton() {
  return (
    <div className="space-y-6">
      <div className="space-y-2 border-b border-border/60 pb-5">
        <Skeleton className="h-4 w-32" />
        <Skeleton className="h-8 w-2/3" />
        <Skeleton className="h-4 w-1/2" />
        <div className="flex gap-2 pt-1">
          <Skeleton className="h-6 w-20" />
          <Skeleton className="h-6 w-24" />
          <Skeleton className="h-6 w-16" />
        </div>
      </div>
      <Skeleton className="h-52 w-full rounded-lg" />
      <div className="grid grid-cols-3 gap-3">
        <Skeleton className="h-32 rounded-lg" />
        <Skeleton className="h-32 rounded-lg" />
        <Skeleton className="h-32 rounded-lg" />
      </div>
      <Skeleton className="h-72 w-full rounded-lg" />
      <Skeleton className="h-48 w-full rounded-lg" />
    </div>
  );
}

// ─── Error state ──────────────────────────────────────────────────────────────

function InvestigationError({ onRetry }: { onRetry: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center py-24 text-center space-y-4">
      <div className="rounded-full border border-dashed border-rose-300 dark:border-rose-700 p-5">
        <AlertCircle className="h-8 w-8 text-rose-500" />
      </div>
      <div className="space-y-1">
        <h2 className="text-lg font-bold text-foreground">
          Investigation Unavailable
        </h2>
        <p className="text-sm text-muted-foreground max-w-sm">
          The investigation workspace could not load the selected opportunity. The opportunity may not have an active investigation.
        </p>
      </div>
      <div className="flex gap-2">
        <Button onClick={onRetry} variant="outline" size="sm" className="gap-1.5">
          <RefreshCw className="h-3.5 w-3.5" />
          Retry
        </Button>
        <Button size="sm" asChild>
          <Link href="/opportunities">
            <ArrowLeft className="h-3.5 w-3.5 mr-1.5" />
            Back to Opportunities
          </Link>
        </Button>
      </div>
    </div>
  );
}

// ─── Empty state ──────────────────────────────────────────────────────────────

function NoHypotheses() {
  return (
    <div className="flex flex-col items-center justify-center rounded-lg border border-dashed border-border/60 py-14 text-center px-4">
      <div className="rounded-full border border-dashed border-border/60 p-4 mb-3">
        <AlertCircle className="h-6 w-6 text-muted-foreground/40" />
      </div>
      <p className="text-sm font-medium text-muted-foreground">
        No Root-Cause Hypotheses Available
      </p>
      <p className="text-xs text-muted-foreground/60 mt-1 max-w-xs">
        The investigation engine has not generated hypotheses for this opportunity yet. Hypotheses are generated by Person B&apos;s backend analysis engine.
      </p>
    </div>
  );
}

// ─── Page inner content (needs Suspense boundary above for useSearchParams) ───

function InvestigationPageContent() {
  const searchParams = useSearchParams();
  const opportunityParam = searchParams.get("opportunity"); // e.g. "OPP-9021"

  const investigationRepo = React.useMemo(() => getInvestigationRepository(), []);
  const opportunityRepo = React.useMemo(() => getOpportunityRepository(), []);

  // UI state
  const [opportunity, setOpportunity] = React.useState<Opportunity | null>(null);
  const [workspace, setWorkspace] = React.useState<InvestigationWorkspace | null>(null);
  const [isLoading, setIsLoading] = React.useState(true);
  const [hasError, setHasError] = React.useState(false);
  const [selectedHypothesisId, setSelectedHypothesisId] = React.useState<string | null>(null);
  const [selectedNodeId, setSelectedNodeId] = React.useState<string | null>(null);

  const loadData = React.useCallback(async () => {
    setIsLoading(true);
    setHasError(false);
    try {
      const opps = await opportunityRepo.getOpportunities();
      let targetOpp: Opportunity | undefined;
      if (opportunityParam) {
        targetOpp = opps.find(
          (o) => o.code === opportunityParam || o.id === opportunityParam
        );
      }
      if (!targetOpp) {
        // No URL param or no match — fall back to highest-priority opportunity
        targetOpp = opps[0];
      }

      if (targetOpp) {
        const ws = await investigationRepo.getWorkspaceByOpportunityCode(targetOpp.code);
        setOpportunity(targetOpp);
        setWorkspace(ws);
        setSelectedHypothesisId(ws?.leadingHypothesisId ?? null);
      }
    } catch (e) {
      setHasError(true);
    } finally {
      setIsLoading(false);
    }
  }, [opportunityParam, investigationRepo, opportunityRepo]);

  React.useEffect(() => {
    loadData();
  }, [loadData]);

  const handleRetry = () => {
    loadData();
  };

  const handleHypothesisSelect = (id: string) => {
    setSelectedHypothesisId((prev) => (prev === id ? null : id));
    // Clear node selection when hypothesis changes
    setSelectedNodeId(null);
  };

  const handleNodeSelect = (nodeId: string) => {
    setSelectedNodeId((prev) => (prev === nodeId ? null : nodeId || null));
    // If node has a hypothesis link, auto-select that hypothesis
    if (workspace && nodeId) {
      const allNodes = flattenTree(workspace.treeRoot);
      const node = allNodes.find((n) => n.id === nodeId);
      if (node?.hypothesisId) {
        setSelectedHypothesisId(node.hypothesisId);
      }
    }
  };

  const selectedHypothesis: InvestigationWorkspaceHypothesis | null =
    workspace && selectedHypothesisId
      ? workspace.hypotheses.find((h) => h.id === selectedHypothesisId) ?? null
      : null;

  if (isLoading) {
    return (
      <PageContainer maxWidth="full">
        <InvestigationSkeleton />
      </PageContainer>
    );
  }

  if (hasError || !opportunity || !workspace) {
    return (
      <PageContainer maxWidth="full">
        <InvestigationError onRetry={handleRetry} />
      </PageContainer>
    );
  }

  const hypothesisStubs = workspace.hypotheses.map((h) => ({
    id: h.id,
    title: h.title,
  }));

  return (
    <PageContainer maxWidth="full">
      <div className="space-y-8">
        {/* 1. Header */}
        <InvestigationHeader
          opportunity={opportunity}
          overallConfidence={workspace.overallConfidence}
        />

        {/* Executive Workflow Guide */}
        <WorkflowStepBanner
          currentStep={3}
          stageName="Deep Diagnostic Investigation"
          summary="Multi-hypothesis root-cause causal graphs analyze primary telemetry anomalies to rule out spurious correlations."
          actionGuidance="Inspect the leading root-cause hypothesis to corroborate empirical evidence."
        />

        {/* Main two-column grid */}
        <div className="grid gap-8 xl:grid-cols-4">
          {/* ── Left column (3/4) ── */}
          <div className="space-y-8 xl:col-span-3">
            {/* 2. Opportunity Context */}
            <OpportunityContextCard opportunity={opportunity} />

            {/* 3. Signal Summary */}
            <SignalSummary signals={workspace.signals} />

            {/* 4. Root-Cause Hypotheses */}
            {workspace.hypotheses.length === 0 ? (
              <NoHypotheses />
            ) : (
              <HypothesisList
                hypotheses={workspace.hypotheses}
                leadingHypothesisId={workspace.leadingHypothesisId}
                selectedId={selectedHypothesisId}
                onSelect={handleHypothesisSelect}
              />
            )}

            {/* 5. Decision Tree */}
            <DecisionTreeVisualization
              treeRoot={workspace.treeRoot}
              hypotheses={hypothesisStubs}
              selectedNodeId={selectedNodeId}
              onNodeSelect={handleNodeSelect}
            />

            {/* 6. Evidence Explorer */}
            <EvidenceExplorer selectedHypothesis={selectedHypothesis} />

            {/* 7. Investigation Summary */}
            <InvestigationSummary workspace={workspace} />

            {/* 8. Next Decision Actions */}
            <NextDecisionActions />
          </div>

          {/* ── Right column (1/4) — Timeline ── */}
          <div className="xl:col-span-1">
            <div className="sticky top-6 space-y-6">
              <InvestigationTimeline events={workspace.timeline} />

              {/* Quick context chip */}
              <div className="rounded-lg border border-border/60 bg-muted/20 p-3 space-y-1.5">
                <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Investigation ID
                </p>
                <p className="font-mono text-xs text-foreground">{workspace.id}</p>
                <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mt-2">
                  Opportunity
                </p>
                <p className="font-mono text-xs text-primary">{workspace.opportunityCode}</p>
                <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mt-2">
                  Hypotheses
                </p>
                <p className="text-xs text-foreground">{workspace.hypotheses.length} competing</p>
                <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mt-2">
                  Overall Confidence
                </p>
                <p className="font-mono text-xs font-bold text-primary">{workspace.overallConfidence}%</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </PageContainer>
  );
}

// ─── Helper: flatten tree nodes ───────────────────────────────────────────────

import { InvestigationTreeNode } from "@/types/investigation-workspace";

function flattenTree(node: InvestigationTreeNode): InvestigationTreeNode[] {
  return [node, ...(node.children ?? []).flatMap(flattenTree)];
}

// ─── Page root (Suspense wraps useSearchParams) ───────────────────────────────
// IMPORTANT: AppLayout (which contains AuthGuard) must appear exactly ONCE —
// as the outer wrapper. The Suspense fallback must NOT contain another AppLayout,
// otherwise two AuthGuard instances compete during hydration and the inner one
// shows the "Verifying Session Security" spinner indefinitely.

export default function InvestigationPage() {
  return (
    <AppLayout>
      <React.Suspense
        fallback={
          <PageContainer maxWidth="full">
            <InvestigationSkeleton />
          </PageContainer>
        }
      >
        <InvestigationPageContent />
      </React.Suspense>
    </AppLayout>
  );
}
