"use client";

import * as React from "react";
import {
  Sparkles,
  Search,
  CheckCircle2,
  Edit3,
  XCircle,
  FileCheck2,
  Dna,
  ArrowRight,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { DecisionStatus } from "@/types/decision-registry";

interface DecisionStatusLifecycleProps {
  currentStatus: DecisionStatus;
  className?: string;
}

export function DecisionStatusLifecycle({
  currentStatus,
  className,
}: DecisionStatusLifecycleProps) {
  const steps = [
    {
      key: "proposed",
      label: "Proposed",
      description: "Generated by DecisionOS",
      icon: Sparkles,
    },
    {
      key: "under_review",
      label: "Under Review",
      description: "Human evaluating evidence",
      icon: Search,
    },
    {
      key: "action",
      label: "Human Decision",
      description: "Approved / Modified / Rejected",
      icon: currentStatus === "approved"
        ? CheckCircle2
        : currentStatus === "modified"
        ? Edit3
        : currentStatus === "rejected"
        ? XCircle
        : CheckCircle2,
    },
    {
      key: "recorded",
      label: "Recorded",
      description: "Preserved in registry",
      icon: FileCheck2,
    },
    {
      key: "dna",
      label: "Decision DNA",
      description: "Lineage & audit record",
      icon: Dna,
    },
  ];

  const getStepState = (stepKey: string) => {
    if (stepKey === "proposed") {
      return "completed";
    }
    if (stepKey === "under_review") {
      if (currentStatus === "proposed") return "upcoming";
      return currentStatus === "under_review" ? "active" : "completed";
    }
    if (stepKey === "action") {
      if (["proposed", "under_review"].includes(currentStatus)) return "upcoming";
      if (["approved", "modified", "rejected"].includes(currentStatus)) return "active";
      return "completed";
    }
    if (stepKey === "recorded") {
      if (["recorded"].includes(currentStatus)) return "active";
      return "upcoming";
    }
    if (stepKey === "dna") {
      return "upcoming";
    }
    return "upcoming";
  };

  return (
    <div className={`rounded-lg border border-border/70 bg-card p-4 sm:p-5 shadow-sm space-y-4 ${className || ""}`}>
      <div className="flex items-center justify-between border-b border-border/40 pb-3">
        <div className="space-y-0.5">
          <h3 className="text-xs font-bold uppercase tracking-wider text-foreground">
            Decision Governance Lifecycle
          </h3>
          <p className="text-[11px] text-muted-foreground">
            Enforced human-in-the-loop progression from opportunity detection to recorded action
          </p>
        </div>
        <Badge variant="outline" className="text-[10px] uppercase font-mono">
          Current State: {currentStatus.replace(/_/g, " ")}
        </Badge>
      </div>

      {/* Lifecycle Flow */}
      <div className="grid grid-cols-1 sm:grid-cols-5 gap-3 pt-1">
        {steps.map((step, idx) => {
          const Icon = step.icon;
          const state = getStepState(step.key);

          const isCompleted = state === "completed";
          const isActive = state === "active";

          return (
            <div
              key={step.key}
              className={`relative rounded-md border p-3 flex flex-col justify-between space-y-2 transition-all ${
                isActive
                  ? "border-primary bg-primary/5 ring-1 ring-primary/30"
                  : isCompleted
                  ? "border-emerald-500/40 bg-emerald-500/5 text-foreground"
                  : "border-border/50 bg-muted/20 opacity-70"
              }`}
            >
              <div className="flex items-center justify-between">
                <div
                  className={`p-1.5 rounded-md ${
                    isActive
                      ? "bg-primary text-primary-foreground"
                      : isCompleted
                      ? "bg-emerald-500 text-white"
                      : "bg-muted text-muted-foreground"
                  }`}
                >
                  <Icon className="h-3.5 w-3.5" />
                </div>
                <span className="text-[10px] font-mono text-muted-foreground">
                  0{idx + 1}
                </span>
              </div>

              <div>
                <h4 className="text-xs font-semibold text-foreground">
                  {step.key === "action" && ["approved", "modified", "rejected"].includes(currentStatus)
                    ? currentStatus.charAt(0).toUpperCase() + currentStatus.slice(1)
                    : step.label}
                </h4>
                <p className="text-[10px] text-muted-foreground line-clamp-1 mt-0.5">
                  {step.description}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
