"use client";

import * as React from "react";
import Link from "next/link";
import { RecommendedStep } from "@/types/dashboard";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowRight, Search, RotateCcw, Sliders, Cpu, CheckCircle2 } from "lucide-react";

interface RecommendedActionsPanelProps {
  steps: RecommendedStep[];
}

export function RecommendedActionsPanel({ steps }: RecommendedActionsPanelProps) {
  const getStepIcon = (route: string) => {
    switch (route) {
      case "/investigation":
        return Search;
      case "/replay":
        return RotateCcw;
      case "/scenario":
        return Sliders;
      case "/optimizer":
        return Cpu;
      default:
        return CheckCircle2;
    }
  };

  return (
    <Card className="border-border/80 shadow-sm">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-500" />
            <CardTitle className="text-base font-bold">
              Recommended Next Decision Actions
            </CardTitle>
          </div>
          <Badge variant="enterprise" className="text-[10px] font-mono">
            CLOSED-LOOP PLAYBOOK
          </Badge>
        </div>
        <CardDescription className="text-xs text-muted-foreground">
          Step-by-step resolution path generated by the Decision Intelligence Engine.
        </CardDescription>
      </CardHeader>

      <CardContent className="pt-1">
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3.5">
          {steps.map((step) => {
            const Icon = getStepIcon(step.route);

            return (
              <Link
                key={step.id}
                href={step.route}
                className="group rounded-xl border border-border/80 bg-muted/10 p-4 flex flex-col justify-between hover:border-primary/50 hover:bg-muted/20 transition-all shadow-sm"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="flex h-6 w-6 items-center justify-center rounded-full bg-primary/10 text-primary font-mono text-xs font-bold">
                      {step.stepNumber}
                    </span>
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">
                      {step.badge}
                    </Badge>
                  </div>

                  <h4 className="text-xs font-bold text-foreground group-hover:text-primary transition-colors leading-snug">
                    {step.title}
                  </h4>
                  <p className="text-[11px] text-muted-foreground leading-relaxed">
                    {step.description}
                  </p>
                </div>

                <div className="pt-3 border-t border-border/50 flex items-center justify-between text-xs text-primary font-medium mt-3">
                  <span className="text-[10px] text-muted-foreground font-mono">{step.engineName}</span>
                  <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-1 transition-transform" />
                </div>
              </Link>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}
